### ISSUE TITLE
No adapter error in kodi when motor switching satellites

### ISSUE THREAD

**Issue by highkick05** [kodi-pvr/pvr.hts#245] opened 2016-10-10 12:35 UTC
Another query regarding selecting channels which need to move motor and while awaiting motor channel times out. giving error message popup 'No adapter' then never retry's to tune once arrives at position.

Can I change anything in pvr.hts configuration to do with this ?

**Comment by Jalle19** [comment] 2016-10-10 14:08
If you get the "no free adapter" notification the problem is in tvheadend. If you get "no input detected" then it's another issue.

**Comment by highkick05** [comment] 2016-10-10 14:17
sorry mate. i will get you the real message being a bit lazy but it's something like that .. do it in a sec

**Comment by highkick05** [comment] 2016-10-10 16:30
Tvheadend HTSP Client
No signal

this is the message, it turns the dish but before it can play the channel .. this message pops up?

**Comment by Jalle19** [comment] 2016-10-11 08:28
Does it not start playing once the dish finishes rotating?

**Comment by highkick05** [comment] 2016-10-11 09:29
nope, not at all. it does looks as if tvheadend does get to play it, but never reaches kodi

**Comment by Jalle19** [comment] 2016-10-11 13:11
@highkick05 do you see the bandwidth counters go up in tvheadend once the rotor has finished?

**Comment by highkick05** [comment] 2016-10-11 13:19
status tab shows bandwidth running normally

**Comment by Jalle19** [comment] 2016-10-11 13:21
Can you post a debug log from Kodi where you leave it trying to play until tvheadend shows there should be data coming through?

**Comment by highkick05** [comment] 2016-10-11 13:25
I can try trace a debug log of it just give me a bit before silly old nag goes to bed

**Comment by Jalle19** [comment] 2016-10-11 20:27
Thanks, please do that. I don't have satellite, much less a motorizes dish so I've never dealt with these kinds of issues. There is probably something we're doing wrong in the addon in this case, I guess the subscription should be retried.

**Comment by Jalle19** [comment] 2016-11-23 13:51
Any update on this?

**Comment by highkick05** [comment] 2016-11-23 14:21
yeah nah man, Sorry I haven't gotten back sooner. I've had a few issues with dish. tvheadend sent my actuator out of it's socket second time in recent weeks, pretty new to using tvheadend still. Furthermore, purchased a dual output LNB that was el cheapo nasty crap which I had to replace again. I've lost patience with it all. I've lost a some good TP's cos I think the frame is bent slightly on the pole / not aligning 100% on birds. I'm getting a new 3m mesh, nearly due anyway

Will see if I have some time to chase those logs, it does look as if the same issue happens when turning dish. & I've noticed a small distance move pvr.hts will fire up the channel (10 so degree's East/West seems to be limit) . If it's longer than certain time that 'No signal' message appears still. Probably needs to keep trying it until it fires up, If user pushes 'STOP' key on remote, or zaps another channel, those 2 are the alternatives to change what the tune is doing. TIMEOUT necessary on a zap ? could keep waiting forever really.

**Comment by Jalle19** [comment] 2016-11-23 14:57
It's very hard to test this reliaby since I don't even have satellite. Normally when Kodi says No input detected you can just keep waiting and it will eventually start playing, but I guess tvheadend is doing something different when it comes to rotors.

**Comment by highkick05** [comment] 2016-11-23 16:00
Above you say, 'I guess subscription should be retried'. 
What's the longest time you could keep it retrying ? It would be great if u make this adjustable in pvr.hts settings. That way people can set it to however long it takes before it gives up completely :)

**Comment by highkick05** [comment] 2016-11-23 17:12
included some logs of me firstly zapping channel on sat I'm fixed already on. then zapping channel on another satellite. the motor turns, but the 'no adapter' kodi message is first thing I see after this it seems the channel will no longer work pvr.hts <-> tvheadend. logs in tvheadend appear to only 

2016-11-24 01:07:55.816 subscription: 0153: No input source available for subscription "192.168.1.247 [ Kodi Media Center ]" to channel "C Music TV" 

and then nothing... just that No signal message still on screen in kodi.

Same process repeated using VLC though to zapp. Tvheadend will actually wait while the motor is turning and eventually it WILL retune the channel once it arrives. Strange huh
here's logs... latest 2 channels end of file are 1 channel/s satellites Apstar 7 -> Asiasat 5 approximately 30 degrees apart.

[kodi.log.txt](https://github.com/kodi-pvr/pvr.hts/files/609510/kodi.log.txt)

**Comment by highkick05** [comment] 2016-11-23 17:17
01:06:06 T:140239876126464  NOTICE: PVRManager - PerformChannelSwitch - switched to channel 'C Music TV'
**01:06:06 T:140239876126464  NOTICE: Creating Demuxer
01:07:55 T:140242064652352  NOTICE: CVideoPlayer::CloseFile()**
01:07:55 T:140242064652352  NOTICE: VideoPlayer: waiting for threads to exit
01:07:55 T:140239876126464  NOTICE: CVideoPlayer::OnExit()
01:07:55 T:140239876126464  NOTICE: Closing stream player 1
01:07:55 T:140239876126464  NOTICE: Waiting for audio thread to exit
01:07:55 T:140239447459584  NOTICE: thread end: CVideoPlayerAudio::OnExit()
01:07:55 T:140239876126464  NOTICE: Closing audio device
01:07:55 T:140239876126464  NOTICE: Deleting audio codec
01:07:55 T:140239876126464  NOTICE: Closing stream player 2
01:07:55 T:140239876126464  NOTICE: waiting for video thread to exit
01:07:55 T:140240355596032   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
01:07:55 T:140240355596032  NOTICE: thread end: video_thread
01:07:55 T:140239876126464  NOTICE: deleting video codec
01:07:55 T:140239876126464  NOTICE: CVDPAU::Release pre-cleanup
01:07:55 T:140239859341056  NOTICE: CMixer::OnExit: Output Thread terminated
01:07:55 T:140239876126464  NOTICE: Closing stream player 3
01:07:55 T:140242064652352  NOTICE: VideoPlayer: finished waiting
01:07:55 T:140242064652352  NOTICE:  (VDPAU) Close
01:07:55 T:140242064652352  NOTICE:  (VDPAU) FiniVDPAUOutput
01:07:55 T:140239867733760  NOTICE: VDPAU::COutput: vdpau gl interop finished
01:07:55 T:140239867733760  NOTICE: COutput::OnExit: Output Thread terminated
01:07:55 T:140242064652352  NOTICE: VDPAU::Close - closing decoder context
01:07:55 T:140242064652352  NOTICE: CVideoPlayer::CloseFile()
01:07:55 T:140242064652352  NOTICE: VideoPlayer: waiting for threads to exit
01:07:55 T:140242064652352  NOTICE: VideoPlayer: finished waiting
01:07:55 T:140242064652352  NOTICE: CVideoPlayer::CloseFile()
01:07:55 T:140242064652352  NOTICE: VideoPlayer: waiting for threads to exit
01:07:55 T:140242064652352  NOTICE: VideoPlayer: finished waiting

in bold. is this it's waiting period before VideoPlayer stop trying ?

**Comment by Glenn-1990** [comment] 2016-11-27 14:40
The "No signal" message is from tvheadend itself, so I'm not sure if we can ignore that. What does the tvheadend log show? Does the streaming actually start in the status tab? Did you set a rotor timeout in tvheadend?

**Comment by Jalle19** [comment] 2017-01-03 21:07
Closing this for now

**Closed by Jalle19** 2017-01-03 21:07 UTC
Labels: Backend issue

**Comment by highkick05** [comment] 2017-01-04 03:10
there is an actual setting in the TV settings part of kodi that I 'think' might fix this.. I did play with it , and I think it may have changed how long it try's the zap. Get back to you in next couple days about it. will test more thoroughly
