### ISSUE TITLE
Can't retrieve picons when password longer than 145 characters

### ISSUE THREAD

**Issue by ggrjevous** [kodi-pvr/pvr.hts#356] opened 2018-02-08 21:32 UTC
When the configured password is longer than 145 characters, Kodi won't show picons (channel icons).
`22:17:16.775 T:12936   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://USERNAME:PASSWORD@serverhostname:9981/imagecache/2977`
Such URL regularly works in browser, replacing USERNAME and PASSWORD accordingly. Picons are back after shortening the password to 145 characters or less.
Also, a similar error is thrown whenever the configured password contains special characters, regardless of its length.

**Comment by Jalle19** [comment] 2018-11-11 19:43
This is a Kodi bug in that case

**Comment by rubdos** [comment] 2019-02-27 16:00
> This is a Kodi bug in that case

I suppose it's a limitation of how kodi processes the generated URLs, in that it doesn't accept basic authentication parameters separately? I have this issue too, seemingly I cannot have `'`'s in my password.

**Comment by tudstudent** [comment] 2020-02-18 09:24
You might try this:
https://github.com/kodi-pvr/pvr.hts/issues/438#issuecomment-587349041

Just found it myself for a similar issue!

**Comment by ksooo** [comment] 2020-12-12 22:32
Duplicate of #386

**Closed by ksooo** 2020-12-12 22:32 UTC
