### ISSUE TITLE
TV guide does not auto update with timer icon

### ISSUE THREAD

**Issue by bas-t** [kodi-pvr/pvr.hts#202] opened 2016-03-01 09:31 UTC
As the title says: running master branch, when I schedule a recording in the guide, it does not show the timer icon unless I first exit the guide and then view it again. Likewise when removing a timer.
Not sure if this is pvr.hts related or maybe kodi.

Running Jarvis everything works fine.

**Comment by ksooo** [comment] 2016-03-01 10:15
I noticed this as well, but only on one if my systems. Reason is currently unknown. I suspect it is a Kodi problem, not a problem with pvr.hts even though it may have been caused by some recent pvr.hts changes. Do you have "async epg transfer" activated in the add-on settings? If so, does turning this off fix the problem?

**Comment by bas-t** [comment] 2016-03-01 10:17
I don't have "async epg transfer" activated. But just out of curiosity, I'll turn it on and see what happens.

**Comment by bas-t** [comment] 2016-03-01 10:20
No difference whatsoever, I guess I'll leave it on then

**Comment by ksooo** [comment] 2016-03-01 10:21
Yeah, leave it on. Should greatly improve pvr startup performance and delivers always live epg data to Kodi - otherwise Kodi polls for epg data only every some minutes.

**Comment by bas-t** [comment] 2016-03-01 10:30
BTW, running master, the only way I ever use the timeshift buffer: jumping forward and backward, seems a lot more solid compared to Jarvis! Thanks a lot.

**Comment by ksooo** [comment] 2016-03-01 10:38
What tvh version are you using?

**Comment by bas-t** [comment] 2016-03-01 10:41
Today's checkout 9e66bb45a49726275a14286f816a71beb3d3507d

**Comment by ksooo** [comment] 2016-03-01 12:01
Oki, using bleeding edge tvh explains the timeshift impovements, although things on the kodi side of things also improved.

**Comment by bas-t** [comment] 2016-03-06 19:41
This issue seems to be fixed (for Debian Stretch). Will test it later on Ubuntu Xenial.

**Comment by bas-t** [comment] 2016-03-06 20:49
I'm not going to investigate whatever fixed this, I'm just happy it's fixed for Ubuntu Xenial too.
Thanks a lot!

**Comment by bas-t** [comment] 2016-03-06 22:36
As it turns out, for confluence skin this issue is not fixed yet. In the new default skin it is, or has never been broken at all.

**Comment by ksooo** [comment] 2016-03-15 08:19
Closing this issue as it is definetly not a pvr.hts problem and you opened http://trac.kodi.tv/ticket/16621 for this.

**Closed by ksooo** 2016-03-15 08:19 UTC
