### ISSUE TITLE
pvr.hts segfaults - kodi 20.0-ALPHA1 (19.90.701) Git:20220701-30fb576edd

### ISSUE THREAD

**Issue by dreamcat4** [kodi-pvr/pvr.hts#583] opened 2022-07-02 15:52 UTC
Hey there,
Updated my systems today. Multiple pkgs, including new nvidia drivers, new version of python, new version of kodi too. (maybe even this addon too, but i have not checked to see).

Anyhow rebooted system, and kodi segfaults during initialization. Looking at the crash log from kodi, the segfault is occuring in something that pvr.hts addon is doing, during it's own addon startup. (and this is happening very consistently in the same place)

```sh
Thread 1 (Thread 0x7f6282737640 (LWP 138409)):
#0  0x000055dfe9767ca4 in PVR::CPVRChannel::UniqueID() const ()
#1  0x000055dfe96a9339 in PVR::CPVRTimers::UpdateEntries(int) ()
#2  0x000055dfe96ab25d in PVR::CPVRTimers::Process() ()
#3  0x000055dfe9173645 in CThread::Action() ()
#4  0x000055dfe9174a5a in  ()
#5  0x000055dfe91759cd in  ()
#6  0x00007f6343adc2b3 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f6344094b43 in start_thread (arg=<optimised out>) at ./nptl/pthread_create.c:442
#8  0x00007f6344126a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
############# END STACK TRACE ###############
```

Full kodi crash log:

https://gist.github.com/dreamcat4/c4151f8015952bc4d607a71c496f5f85#file-kodi-crash-log-L56

So just to confirm that, I removed the pvr.hts addon from ubuntu (its .deb pkg). And then re-ran kodi app again. And the crash dissapears, it starts up normally. Then if i reinstall the .deb via apt... kodi will next time lauch and ask the user if they want to re-enable the pvr.hts Tvheadend addon. At which point, if selecting "yes"... then kodi immediately crashes / segfaults again. During the addon enablement. Wheras if i select "no", then it doesn't.

Again, I am not sure yet which pkg update exactly triggered this to start happening (if it was the new kodi pkg or an incremental update to python 3.10 version, or the pvr.hts addon itself). 

But here's the current version installed on my system:

```sh
$ apt search kodi | grep -i hts
kodi-pvr-hts/jammy,now 6:20.3.0-1~jammy amd64 [installed,automatic]
kodi-pvr-hts-dbg/jammy 6:20.3.0-1~jammy amd64
kodi-pvr-tvheadend-hts/jammy,jammy 6:20.3.0-1~jammy all

$ kodi.bin --version
Kodi Media Center 20.0-ALPHA1 (19.90.701) Git:20220701-30fb576edd
Copyright (C) 2005-2021 Team Kodi - http://kodi.tv

$ apt show python3.10 -a
Package: python3.10
Version: 3.10.5-1+focal1
Status: install ok installed
Priority: optional
Section: python
Maintainer: Matthias Klose <doko@debian.org>
Installed-Size: 627 kB
Depends: python3.10-minimal (= 3.10.5-1+focal1), libpython3.10-stdlib (= 3.10.5-1+focal1), mime-support
Suggests: python3.10-venv, binutils
Download-Size: unknown
APT-Manual-Installed: no
APT-Sources: /var/lib/dpkg/status
Description: Interactive high-level object-oriented language (version 3.10)
 Python is a high-level, interactive, object-oriented language. Its 3.10 version
 includes an extensive class library with lots of goodies for
 network programming, system administration, sounds and graphics.

Package: python3.10
Version: 3.10.4-3
Priority: important
Section: python
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Matthias Klose <doko@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 626 kB
Depends: python3.10-minimal (= 3.10.4-3), libpython3.10-stdlib (= 3.10.4-3), media-types | mime-support
Suggests: python3.10-venv, python3.10-doc, binutils
Breaks: python3-all (<< 3.6.5~rc1-1), python3-dev (<< 3.6.5~rc1-1), python3-venv (<< 3.6.5-2)
Task: minimal, server-minimal
Download-Size: 488 kB
APT-Sources: http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages
Description: Interactive high-level object-oriented language (version 3.10)
 Python is a high-level, interactive, object-oriented language. Its 3.10 version
 includes an extensive class library with lots of goodies for
 network programming, system administration, sounds and graphics.

[id:~/.kodi/userdata] $ python3 --version
Python 3.10.5
```

Hopefully we can work together to help fix this. In the meantime (while waiting for you to respond) I might try to find out some more infos. Or try rolling back certain pkgs. Many thanks for your time / consideration here.

**Comment by dreamcat4** [comment] 2022-07-02 16:20
ah... maybe because its kodi nightly builds ppa. perhaps should roll it back or something

**Comment by phunkyfish** [comment] 2022-07-02 16:21
If the API has changed between the alpha and the nightlies it will work again when the next alpha is released.

**Comment by ksooo** [comment] 2022-07-02 17:56
> Looking at the crash log from kodi, the segfault is occuring in something that pvr.hts addon is doing, during it's own addon startup. (and this is happening very consistently in the same place)

 Definitely not an add-on issue. As of now I don't know exactly what is going wrong, but it's nothing that bombs due an API incompatibility and it does not crash within the add-on code.

**Comment by dreamcat4** [comment] 2022-07-02 18:06
ah ok... so maybe if there is different PVR addon (for testing purpose, with fake calls?) like a dummy pvr addon just stubs?

to be able to exercise the same PVR api method

**Comment by ksooo** [comment] 2022-07-02 18:08
pvr.demo

**Comment by ksooo** [comment] 2022-07-02 18:09
> to be able to exercise the same PVR api method

which one exactly? i cannot see any pvr add-on api call in the call stacks of the supplied crash log

**Comment by dreamcat4** [comment] 2022-07-02 19:09
what about this then?

```sh
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055dfe9767ca4 in PVR::CPVRChannel::UniqueID() const ()
```

**Comment by ksooo** [comment] 2022-07-02 20:18
This is not an add-on API call. I feel like you're mixing up terminology. 

Anyway, ofc your are welcome to test whatever you want and to report the results. 

However, this issue should be closed as I am very confident that the cause for the crash is not located in the code of pvr.hts. The root cause of the crash lies in xbmc code, thus the issue should be opened and discussed there. No worries, I will pick it up there. ;-)

**Closed as completed** 2022-09-06 21:42 UTC
