### ISSUE TITLE
User has no access / server error - if broadcasts have been shifted

### ISSUE THREAD

**Issue by alexhass** [kodi-pvr/pvr.hts#345] opened 2017-12-05 22:34 UTC
There is a problem in htsp client if a broadcast has been moved during a day. In such a case you are no longer able to record anything on this specific channel. On other channels I can record without issues. 

You only get a pvr backend error and get told to review the log. I reviewed the log and found this misleading errors:

`
22:07:13.837 T:140576779376384  NOTICE: VDPAU::COutput registered output surfaces
22:07:13.945 T:140577409980096  NOTICE: Previous line repeats 6 times.
22:07:13.945 T:140577409980096  NOTICE:  (VDPAU) Close
22:07:13.946 T:140577409980096  NOTICE:  (VDPAU) FiniVDPAUOutput
22:07:13.947 T:140576177997568  NOTICE: VDPAU::COutput: vdpau gl interop finished
22:07:13.950 T:140576177997568  NOTICE: COutput::OnExit: Output Thread terminated
22:07:13.991 T:140577409980096  NOTICE: GL: Using VDPAU render method
22:07:13.991 T:140577409980096  NOTICE: GL: NPOT texture support detected
22:07:13.991 T:140577409980096  NOTICE: GL: Using GL_ARB_pixel_buffer_object
22:07:13.991 T:140577409980096  NOTICE: Using GL_TEXTURE_2D
22:07:14.502 T:140574799681280 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
22:07:15.523 T:140574799681280 WARNING: Previous line repeats 2 times.
22:07:15.523 T:140574799681280  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 36363
22:07:16.136 T:140574799681280 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
22:07:16.802 T:140574799681280  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: lost diff
22:07:17.137 T:140574799681280  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 20000
22:07:23.550 T:140577409980096   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command addDvrEntry failed: User does not have access
22:07:23.551 T:140577409980096   ERROR: PVR - AddTimer - addon 'HTPC:127.0.0.1:9982' returned an error: server error
22:07:23.551 T:140577409980096   ERROR: PVR - AddTimer - cannot add timer to client '2025648334': server error
22:08:23.821 T:140577409980096   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command addDvrEntry failed: User does not have access
22:08:23.821 T:140577409980096   ERROR: PVR - AddTimer - addon 'HTPC:127.0.0.1:9982' returned an error: server error
22:08:23.821 T:140577409980096   ERROR: PVR - AddTimer - cannot add timer to client '2025648334': server error
22:08:41.446 T:140577409980096   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command addDvrEntry failed: User does not have access
22:08:41.446 T:140577409980096   ERROR: PVR - AddTimer - addon 'HTPC:127.0.0.1:9982' returned an error: server error
22:08:41.446 T:140577409980096   ERROR: PVR - AddTimer - cannot add timer to client '2025648334': server error
22:12:14.428 T:140574799681280 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
22:12:28.188 T:140577409980096   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command addDvrEntry failed: User does not have access
22:12:28.188 T:140577409980096   ERROR: PVR - AddTimer - addon 'HTPC:127.0.0.1:9982' returned an error: server error
22:12:28.188 T:140577409980096   ERROR: PVR - AddTimer - cannot add timer to client '2025648334': server error
`

Just to show you how this looked like in kodi, see the below screenshot. Here you can see „report münchen“ and „tagesthemen“ are „splitted“ into two parts. The reason seems to be a program that shifted every program by 15minutes to future during the day and epg received these updates / delayed start times.

![628e528c-7d0d-44d3-b1bc-fd158c547797](https://user-images.githubusercontent.com/4450722/33633894-a4296740-da12-11e7-9224-83c778b6fb6a.jpeg)

After I enables htsp client debugging the client was restarted and the programs are no longer splitted and the issue disapeared.

![708751f3-23e7-4e79-bfc6-225614dadbda](https://user-images.githubusercontent.com/4450722/33634137-70d1a1cc-da13-11e7-9494-894cde5f0848.jpeg)

This issue is really annoying and the only workarounds I found is restarting libreelec what suxxx extreme if other recordings are running. Aside - recording via tvheadend webfrontend does not cause failures at the same time.

This is libreelec 8.2.0 with dvb-s2 and tvheadend 4.2.3 and latest htsp client.

**Comment by ksooo** [comment] 2017-12-08 15:38
Does this also happen with libreelec 9.0.0 (nightly), which is Kodi 18 (pre-alpha) and tvh 4.2.3?

**Comment by ksooo** [comment] 2017-12-08 15:40
> This issue is really annoying and ... what suxxx extreme

 Please stop this offending comments if you want to get help. Such s**t helps zero and only makes devs angry.

 If you would be cute enough to know how to restart Kodi without restating the whole box, including tvheadend, it would "suck" much less, I guess.

**Comment by alexhass** [comment] 2017-12-08 16:42
Please do not change my sentences. This was not offending to any person - just about the situation I’m in. I said - restarting libreelec as a workaround suxx. How would you name it - if you need to restart your htpc to solve such an issue? Do you like to hear - „cool I love restarts to break 2 other running recordings only to activate a 3rd recording or broken recordings are cool - I love it“. Breaking recordings is not a positive situation!

Relax. Back to the bug.

I do not have 9.x installed. Reproducing this situation is difficult as it requires broadcasters to change program schedules first...

It seems to be clear that tvh client has a problem with tvh server. Tvh server itself has no issue with this recordings. As noted, after enabling the debug mode in tvh client the issue was resolved as tvh client was restarted to enable the debugging. No other service was restarted. Kodi was not restarted.

I could keep debugging of tvh client enabled if this helps. But i have no idea when a schedule may change again and what data is required to debug the issue.

How can a communication issue between tvh client and server be a kodi issue? Kodi seems not involved in EPG sync if I’m not wrong. I‘m confused...

**Comment by ksooo** [comment] 2017-12-08 16:58
> How would you name it - if you need to restart your htpc to solve such an issue? Do you like to hear - „cool I love restarts to break 2 other running recordings only to activate a 3rd recording or broken recordings are cool - I love it“. Breaking recordings is not a positive situation!

I would call this I'm to dumb to restart just Kodi instead of the whole system, losing running recordings just because I'm clueless. And no, I don't want to calm down as I hate clueless people using strong words in a instead of just masking neutral and objective statements - especially, as the scenario for sure dies not hit you many times a week. Back to tut bug? No, not interested.

**Comment by ksooo** [comment] 2017-12-08 17:08
> How can a communication issue between tvh client and server be a kodi issue? 

 Nobody said it's a Kodi issues. It could be, but that has to be investigated.

> Kodi seems not involved in EPG sync if I’m not wrong

 You are wrong. Kodi regularly pulls the EPG data from the client and syncs its epg database after having  new data.

BTW: If you know how to restart the add-on, forcing a reload of epg data, which solves the problem, why are you whining that you have to restart libreelec?

**Comment by alexhass** [comment] 2017-12-08 19:45
I‘m not very long aware of the fact that enabling debugging of tvh client solved the issue. When the issue reoccurs you only have one try to isolate the possible root cause.

Why I‘m „whining“? I expect that I need to restart my libreelec only for major updates and it may run months without a restart (including every addon). This was possible with openelec 6 and 7 and windows meda center 7. wmc was running 3-6 months without a restart. OE 6/7 was close to 8-10 weeks. LE 7.90.10 - no longer than 5 days without a kodi / tvh server crash. LE 8.2 looks much better, but official releases are still broken. CVH told all his fixes are only available in 9.x and his unofficial builds. It looks like this stability fixes cannot go into 8.x. But this is OT here.

Don‘t take words in a non-mother language so serious, please. I just documented a problem that should be resolved. Stability is my only concern.

**Comment by ksooo** [comment] 2017-12-08 21:45
> When the issue reoccurs you only have one try to isolate the possible root cause.

 Almost same situation here, but even worse - with the difference that I never ran into this problem and therefore cannot reproduce anything. That's why I asked you in the first place to test this with LE9 - which you did not wanted to do. End of story. You know, it's all a question of effort and gain. Nobody of us 100% volunteer Kodi contributors has the time to debug very difficult to reproduce EDGE cases. seriously, how often did the problem hit you?

> I expect that I need to restart my libreelec only for major updates and it may run months without a restart (including every addon). 

 Honestly, I told you more than once that you do NOT need to restart libreelec to workaround your issue. Enabling/disabling the addon is enough. Thus, your complaint regarding loosing running recordings is pointless, okay?

> CVH told all his fixes are only available in 9.x and his unofficial builds. 

 AFAIK, CVH does not provide no fixes neither for pvr.hts nor for Kodi. What he does is (a very good job) on providing recent stable (4.2.x) build of tvheadend server for liebreelec. So, there is nothing to backport that would help you.

**Comment by Jalle19** [comment] 2017-12-09 08:37
Have you tried enabling asynchronous EPG transfer in the addon settings?

**Comment by alexhass** [comment] 2017-12-09 13:26
> Seriously, how often did the problem hit you?
LE 8.2 is installed for about ~10 days. So I have seen the bug 2 times in last 10 days. Could happened unseen more often.

> AFAIK, CVH does not provide any fixes for pvr.hts or Kodi. What he does is (a very good job) on providing recent stable (4.2.x) builds of tvheadend server for libreelec. So, there is nothing to backport that would help you.
I do not know what he fixed in the kernel. But his LE82 works works without artefacts on TV where the official LE82 is seriously broken since every version later than 7.90.010. He told in the forum that this is known and cannot added to official 8.x versions.

> Have you tried enabling asynchronous EPG transfer in the addon settings?
Yes, this was and is enabled.

I could theoretically test with 9.x, but it is not that easy as all data need to be moved.

**Comment by CvH** [comment] 2017-12-09 14:28
> AFAIK, CVH does not provide any fixes for pvr.hts or Kodi

ofc I doesn't change anything at pvr.hts

> I do not know what he fixed in the kernel. But his LE82 works works without artefacts on TV where the official LE82 is seriously broken

thats just an linux kernel driver problem (the usual mess) but this has no impact at this problem here

> I could theoretically test with 9.x, but it is not that easy as all data need to be moved.

you can try LE9 at an VM (currently only VMWarePlayer/Worksation supported, Player is free)
`install LE8.2-Generic.ova at VM, resize hdd before first start, update to latest Milhouse build, done`

**Comment by Jalle19** [comment] 2017-12-09 14:50
Try with async EPG disabled too

**Comment by alexhass** [comment] 2018-03-14 19:34
Today the program has changed. ARD planed to show the movie „FilmMittwoch im Ersten: Elster“ starting at 20:15. But the program has changed and „Farbe bekennen“ (from 20:15 to 20:30) was inserted.

Kodi has NOT shown the change! „FilmMittwoch“ was still shown as starting at 20:15 and the rest of the evening was also incorrect. In pvr settings I deleted all data and this has reloaded the epg data and the epg was loaded with the “Farbe bekennen“ in the timeline.

So, the disabling of async epg load has therefore not improved anything.

I‘m on devel LE 9 version build 0116 just for the notes that LE9 is 100% not solving the bug reported here. It only adds another bug. Now it is clear that both async and sync epg have bugs and are not properly updated in background.

**Comment by alexhass** [comment] 2018-03-26 17:36
Super guys. We had wintertime/summertime change last sunday 2:00 and was shifted to 3:00.

Today everything in epg was 1h wrong. Movies starting at 20:15 have started at 19:15 per epg. What the heck is going on here??? I‘m on  build 0207 of libreelec 9 dev.

I hope this is enough to work on this easy to reproduce issues now. Ignoring does not really fix the bugs...

**Comment by zenvoid** [comment] 2020-02-27 23:30
Hello, this issue seems to happen very frequent on the EPG of my country, almost daily :(
I have no knowledge of Kodi internals, but I could test things or send logs if its of any use.

**Comment by ksooo** [comment] 2021-01-10 22:00
Is this still an issue with latest Kodi v19 nightly builds? If I get no response within two weeks, I will close this issue.

**Comment by martin3000** [comment] 2021-05-30 21:49
I had this problem in the last days.
Clearing the TV data and starting kodi again seems to fix it.

**Comment by CV8R** [comment] 2021-08-04 05:28
Just upgraded to Kodi 19.1 - same log symptoms as detailed in Kodi Tvheadend forum here:

[https://forum.kodi.tv/showthread.php?tid=342906&pid=3052786#pid3052786](url)

Multiple prior recordings work fine but when you get to a particular event it fails.  My speculation is per the above that when the broadcaster shifts the even start and/or end time we run into this problem. Using Guide -> "Clear data" fixes it.  However, this workaround isn't ideal for my technically challenges and a little more mature parents.

2021-08-04 15:14:32.485 T:13792   ERROR <general>: AddOnLog: pvr.hts: Command addDvrEntry failed: User does not have access
2021-08-04 15:14:32.485 T:13792   ERROR <general>: AddTimer: Add-on 'Tvheadend:10.0.3.1:9982' returned an error: server error

I am located in Australia, not sure if that helps any...

**Comment by jansohn** [comment] 2021-08-04 21:54
I've also been hit by this problem multiple times. It still happens with 19.1.

**Comment by ksooo** [comment] 2021-08-05 06:15
Please ensure you have "async EPG transfer" enabled in pvr.hts addon settings and report back whether this fixes the problem.

With this setting enabled, Kodi's EPG will get updated as soon as data will be updated by tvheadend (push).

With this setting disabled, Kodi's EPG data will be refreshed using the interval set in Kodi's PVR settings (pull). As this interval is 120 mins by default, Kodi's EPG data can be off by 2 hours!

**Comment by CV8R** [comment] 2021-08-06 07:35
pvr.hts addon wasn't set to  "async EPG transfer" so I enabled in addon settings.

Left Kodi and tvheadend server alone which involved exiting Kodi and leaving tvheadend sleeping and waking for daily use with other Kodi clients. (Not sure if sleeping tvheadend is a clue hence the mention).

After roughly 24 hours tested again and on the first recording attempt with async enabled the recording failed - below is a log snippet.

I ran the test again giving more time and in this second test some recordings worked, and some failed.  I have a full log of the second test if that helps.

First recording attempt after async change log snippet:

`2021-08-06 17:19:50.527 T:15528    INFO <general>: AddOnLog: pvr.hts: Request async EPG (7 days)
2021-08-06 17:19:50.527 T:15528    INFO <general>: AddOnLog: pvr.hts: Async updates requested
2021-08-06 17:19:50.529 T:3140     INFO <general>: PVR Manager: Starting
2021-08-06 17:19:50.578 T:10552    INFO <general>: PVR Manager: Started
2021-08-06 17:19:50.603 T:16972    INFO <general>: AddOnLog: pvr.hts: Async updates initialised
2021-08-06 17:20:03.641 T:4508     INFO <general>: Loading skin file: MyPVRChannels.xml, load type: KEEP_IN_MEMORY
2021-08-06 17:20:07.413 T:4508     INFO <general>: Loading skin file: MyPVRGuide.xml, load type: KEEP_IN_MEMORY
2021-08-06 17:20:11.517 T:4508     INFO <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
2021-08-06 17:20:13.367 T:4508    ERROR <general>: AddOnLog: pvr.hts: Command addDvrEntry failed: User does not have access
2021-08-06 17:20:13.367 T:4508    ERROR <general>: AddTimer: Add-on 'Tvheadend:10.0.3.1:9982' returned an error: server error`

**Comment by ksooo** [comment] 2021-08-06 08:04
Could you for testing only prevent tvheadend from sleeping and report back here?

**Comment by CV8R** [comment] 2021-08-06 23:10
Let tvheadend stay up all night and KODI client connected. Tried this morning and it failed on the first ABC program. Interesting, the guide data was blank for many channels. On the blank ones instant record worked.  On the programs where there was guide data for longer programs it failed.  For the shorter programs it worked.  See screen caps.


Missing Data failed on first ABC TV entry Weekend Breakfast:

![KodiEPG](https://user-images.githubusercontent.com/39397297/128578672-cd1fcaa5-956c-40ca-af18-7e6f6c0a95e8.png)


10 Canberra, PRIME7 Canberra and Channel 9 all failed:

![KodiEPG_1](https://user-images.githubusercontent.com/39397297/128578678-b279be80-5132-4300-8c06-29dae8d08819.png)



ABC NEWS Weekend Breakfast failed:

![KodiEPG_2](https://user-images.githubusercontent.com/39397297/128578680-1f24c64c-1e1f-4119-8866-3da51223fd15.png)


I then went and Clear Data but going back to the Kodi Guide had some data in channels and not others. In this case the ABC NEWS would now record.

See cap:

![KodiEPG_3](https://user-images.githubusercontent.com/39397297/128578987-05ddc7a3-28db-43c1-b5a6-e2a8ace3d8ab.png)


Restarting Kodi restored data to some channels but not others.  Those that were failing now work.

**Comment by ksooo** [comment] 2021-08-07 06:14
Could it be that it fails for all programs already running when you want to start recording them and that it works for all programs starting in the future?

**Comment by ksooo** [comment] 2021-08-07 06:19
I have the feeling that tvheadend already has deleted the EPG data for the failing programs. Kodi keeps "past" programs according to the respective PVR setting.

Could you please check in the tvheadend web UI that the failing programs are still known to tvheadend (or not, which is what I do assume).

**Comment by CV8R** [comment] 2021-08-07 08:12
Looks like you may have found 2 issues... I found one program displayed in the GUI as currently playing half/half on the vertical line on the guide for now time.  That program failed and was not in the guide data for tvheadend. Unfortunately I didn't capture that. In the Kodi log loos like the same log lines but I wasn't looking for it and not 100% on that.  I will try and reproduce this casewith a clean log.

However, a recording also failed on 24 ABC NEWS recording Planet America it is clearly still in the tvhedend guide data.

`2021-08-07 17:53:02.858 T:13744   ERROR <general>: AddOnLog: pvr.hts: Command addDvrEntry failed: User does not have access
2021-08-07 17:53:02.858 T:13744   ERROR <general>: AddTimer: Add-on 'Tvheadend:10.0.3.1:9982' returned an error: server error`

![KodiEPG_4](https://user-images.githubusercontent.com/39397297/128593292-8ddf0010-20d0-4e11-9dc4-3217e15b0cf6.png)

**Comment by ksooo** [comment] 2021-08-07 11:05
Okay, it seems that we have a problem with in-progress programs. tvheadend seems to withdraw epg data for programs still in progress and under some circimstances it refuses to record on in-progress shows it has EPG data for. 

Unfortunately, neither pvr.hts nor Kodi can do something about that. This has to be fixed in tvheadend, sorry.

**Comment by CV8R** [comment] 2021-08-18 05:14
I have had a little more time to look and think about this.  It is interesting that a combination of Clear Data in PVR & Live TV settings and then a disable/enable of pvr.hts, without a restart of KODI or tvheadend, will allow recordings to work for the programs that were failing. I say Clear Data and disable/enable because the guide is empty and doesn't re-populate after the Clear Data, unless I restart pvr.hts. Because I cannot see the guide data in the UI I am not sure which step resolves it. Closing KODI and restarting it does not appear to make any difference, failed recordings, still fail.

I was just in the process of trying to capture a wireshark, of the messaging before and after but it all took to long and I missed the end of the recording...  Anyway, let me know if a wireshark will help.

It has me thinking though if it would it be an option for pvr.hts to try and re-load the EPG data and try again should the request fail, rather than giving up on the first attempt?

**Comment by malvinas2** [comment] 2024-10-01 01:38
Has this issue ever been resolved? I stumbled about the same error message, running Kodi 21.1/LibreElec 12.0.1 on an Intel NUC and HTS Tvheadend 4.3-2167~g583de2330 / Ubuntu 22.04
A restart of the pvr-addon and/or Kodi is not sufficient, I also have to clear the EPG data. Async EPG transfer disabled/enabled doesn't seem to make any difference. 

```
Zeile 742500: 2024-10-01 02:49:57.615 T:2010    error <general>: AddOnLog: pvr.hts: Command addDvrEntry failed: Benutzer hat keinen Zugang
Zeile 742501: 2024-10-01 02:49:57.615 T:2010    error <general>: AddTimer: Add-on 1 returned an error: server error
```

EDIT: 
If I remember correctly I tried the following steps in the order described below: 
- restarted pvr.hts, no change hence restarting Kodi, no change
- restarted pvr.hts, cleared epg-data, restarting Kodi, no change resp. EPG data for some channels (e.g. RTL HD) haven't been reloaded, although they were available in the TvH GUI all the time. The update interval in Kodi is just 15 min, but even after this time the corresponding data wasn't updated. 
- restart of tvheadend-service on the NAS, finally EPG for all channels was available in Kodi and recordings worked again

(actually the fact that after clearing guide data the information is not fetched for all channels would be another issue. Does the re-import work correctly? Or maybe a menu entry "Fetch all EPG data" wouldn't be too bad)

**Comment by ksooo** [comment] 2024-10-01 05:58
Please post a full debug log. With pvr component debugging enabled. Then I can see for example exact version numbers, configuration details etc.

**Comment by ksooo** [comment] 2024-10-01 05:59
I think this is a tvheadend bug. The issue should be reported there.

**Comment by ksooo** [comment] 2024-10-01 06:03
If pvr.hts setting async epg update is enabled, kodi setting epg update interval is non functional. pvr.hts will push updates to kodi the moment they arrive from tvheadend. If tvh pushes nothing, it is a bug in the backend, not the addon.

**Comment by CV8R** [comment] 2024-10-01 08:32
I have had another crack at taking logs for you because this is consistent with Kodi.  When testing I came across something very interesting.

I tried some recording start then stop if it worked.

Recorded:

Antiques Roadshow - Recorded Ok
Long Lost Family - Recorded Ok
ABC News Hour - Recorded OK

However, I noticed that the ABC News Hour jumped and created an empty spot - the EPG was updated.  This happened after hitting record, or stop cannot recall which or it may be co-incidental. I then tried ABC News Hour again and the error message appeared (record could not start) the log showed `Command addDvrEntry failed: User does not have access`.

Also interesting, there is nothing appearing in the tvheadend debug log, as if Kodi never tries once this error starts occuring.  See screen shot.

So it appears something changed in the guide and from that point Kodi is no longer trying.

<img width="2808" alt="Screenshot 2024-10-01 at 6 02 11 PM" src="https://github.com/user-attachments/assets/6adf2dd2-f2c2-43e8-9f37-7f703c4bf611">
<img width="2808" alt="Screenshot 2024-10-01 at 6 01 57 PM" src="https://github.com/user-attachments/assets/0e2fe2fa-dbb0-4477-9dbd-1c83b1a5facb">

<img width="1998" alt="Screenshot 2024-10-01 at 6 23 09 PM" src="https://github.com/user-attachments/assets/6135a803-c1b4-4481-9c54-189d71a128ea">

Log [https://pastebin.com/Lwt6D74m](url)

**Comment by ksooo** [comment] 2024-10-01 09:13
> 2024-10-01 17:58:57.552 T:2911436    info <general>: Starting Kodi (20.2 (20.2.0) Git:20230629-5f418d0b13). Platform: macOS x86 64-bit

Kodi 20 is EOL, sorry.  No support anymore.

If you can reproduce with Kodi 21 or 22, please report back with respective logs, thanks.

**Comment by ksooo** [comment] 2024-10-01 09:17
> "User does not have access"

This is what tvheadend returns as error description once the call to "addDvrEntry" fails. If there is nothing in the tvheadend logs, they simply do not log this error, for whatever reason.

As I stated several times here: This seems to be a tvheadend bug. Please open an issue there. => https://github.com/tvheadend/tvheadend/issues

**Comment by CV8R** [comment] 2024-10-01 09:56
For what it's worth it took 2 minutes to replicate with version:

```
2024-10-01 19:44:23.921 T:2979770    info <general>: Starting Kodi (21.1 (21.1.0) Git:20240817-183eb85f10). Platform: macOS ARM 64-bit
2024-10-01 19:44:23.921 T:2979770    info <general>: Using Release Kodi x64
2024-10-01 19:44:23.921 T:2979770    info <general>: Kodi compiled 2024-08-17 by Clang 14.0.0 (clang-1400.0.29.202) for macOS ARM 64-bit version 11.0 (110000)
```
```
2024-10-01 19:48:12.756 T:2979770   error <general>: AddOnLog: pvr.hts: Command addDvrEntry failed: User does not have access
2024-10-01 19:48:12.756 T:2979770   error <general>: AddTimer: Add-on 1 returned an error: server error
```

Issue opened with tvheadend. [https://github.com/tvheadend/tvheadend/issues/1766](url)

**Comment by Jalle19** [comment] 2024-10-01 10:52
https://github.com/tvheadend/tvheadend/issues/1766 linking this here again since the previous link is broken (should make this issue show up as a linked issue on the other end as well)

**Comment by malvinas2** [comment] 2024-10-01 20:53
> If pvr.hts setting async epg update is enabled, kodi setting epg update interval is non functional. pvr.hts will push updates [...]

I know. I just wanted to emphasize that it doesn't seem to make a difference wether Kodi pulls the data (async disabled) or TvH pushes the data (async enabled). 

I enabled pvr and epg component debugging, but unlike CV8R, I find it difficult to produce the error because I need a faulty EPG to do so. At the moments everything works as expected.

**Comment by CV8R** [comment] 2024-10-02 04:35
Bringing the discussion back here - early testing - but great news so far.  Looks like it's fixed with the changes to Epg.cpp.  

I did notice two odd things whilst testing that may or may not be related.

1. A section of blank EPG and when recording the next event I can cancel the recording from the blank section. See screenshot below.

2. I could not enable a recording for a program immediately after a scheduled timer record (with ongoing end padding time). 


![Kodi_Empty_EPG](https://github.com/user-attachments/assets/98f63782-ab55-42d2-b862-60f6de3aeb4b)

Let me know if we need issues for these two.

Building Kodi on Kubuntu 24.04 was an experience!

**Comment by ksooo** [comment] 2024-10-02 05:56
Great to hear that the fix works for you.
For the other problems please open two issues for kodi. Those are most probably not caused by the addon. 

And please describe the problems as detailed as you can, include logs with pvr and epg component logging enabled. I will most probably not be able to reproduce myself so analysis will rely on logs and description.

**Comment by malvinas2** [comment] 2024-10-02 17:16
A little bit late to the party .... 
[kodi.log](https://github.com/user-attachments/files/17233774/kodi.log)

**Closed** 2024-10-03 18:23 UTC
