### ISSUE TITLE
Remove unnecessary sending username:password in streaming request

### ISSUE THREAD

**Issue by jkscz** [kodi-pvr/pvr.hts#368] opened 2018-06-14 07:58 UTC
Please can you remove username:password from generated streaming URL, which is not needed, because URL contains streaming ticket autenticated thru HTSP protocol (like TVHGuide does)? Removing unnecessary sending username and password in unecrypted form will increase communications security.

**Comment by Jalle19** [comment] 2018-06-14 08:18
Which URLs are you talking about?

**Comment by jkscz** [comment] 2018-06-14 16:02
Sorry for mistake, problem is related to communication between server and client when channel icons are downloaded. In communication over HTTP protocol, all imagecache requests are authorized thru basic autentification with unencrypted username and password. Possible solution is move imagecache request to main HTSP communication (where si encrypted password).

Captured HTTP communication:

> Hypertext Transfer Protocol
    HEAD /imagecache/152 HTTP/1.1\r\n
    Host: tvh.server.net\r\n
    Authorization: Basic qqqqqqqqqqqq\r\n
    User-Agent: Kodi/17.6 (Linux; Android 8.0; SM-GXXXF Build/R16NW) Android/8.0.0 Sys_CPU/aarch64 App_Bitness/64 Version/17.6-Git:20171119-ced5097\r\n
    Accept: */*\r\n
    Accept-Charset: UTF-8,*;q=0.8\r\n
    \r\n
    [Full request URI: http://tvh.server.net/imagecache/152]
    [HTTP request 1/1]
    [Response in frame: 39]

**Comment by Jalle19** [comment] 2018-06-14 20:21
HTSP is not encryptes eithee AFAIK

**Comment by perexg** [comment] 2018-11-30 11:44
TVH supports the digest HTTP authentication. Please, add the support for the digest authentication.

**Comment by ksooo** [comment] 2020-12-12 22:25
Duplicate of #386

**Closed by ksooo** 2020-12-12 22:25 UTC
