### ISSUE TITLE
Recording lifetime "forever" does not work

### ISSUE THREAD

**Issue by ksooo** [kodi-pvr/pvr.hts#201] opened 2016-02-29 13:51 UTC
At least with tvh 4.0.x (checked 4.0.8) this setting does quite the opposite of what it is supposed to do. The scheduled recording will be done just fine, but immediately after the recording is finished, the respective tvh database entry will be deleted. Seems, that it expires immediately (retention = 0 days). For the user it seems that the recording never happened as there is neither an entry in "finished recordings" nor in "failed recordings" and ofc no entry in Kodi timers UI. ;-)

I did experience this as well as a user in the forum. http://forum.kodi.tv/showthread.php?tid=262086

@Glenn-1990 maybe you can have a look? Maybe some sort of data overflow on tvh side? The "forever" value is quite big (2^31). Just guessing.

**Comment by Glenn-1990** [comment] 2016-02-29 13:56
I'll look into this, seems strange as I tested with 4.0 and 4.1

**Comment by Glenn-1990** [comment] 2016-02-29 14:37
It seems like a bug on the tvh side, we can just remove that option for 4.0? 
The retention/removal code was rewritten for 4.1, so that should just work.

**Comment by ksooo** [comment] 2016-02-29 16:30
> It seems like a bug on the tvh side, we can just remove that option for 4.0? 

 Yeah remove it for 4.0 as it actually is a fake anyway ("forever" by huge number of days, but technically not "forever").

 Please don't forget to change the default setting label like you already did for "until disk space needed" (tvh 4.1+ or so).

**Comment by ksooo** [comment] 2016-02-29 16:32
> It seems like a bug on the tvh side

Just a question. Have you debugged this? Is it a fact that it does not work for tvh 4.0 and that is does work for 4.1?

**Comment by Glenn-1990** [comment] 2016-02-29 21:56
I tested it partly, I have no acces to a tuner ATM, but everything is passed correctly to tvh.
Also I can see some possible time_t overflows in the 4.0 code:
https://github.com/tvheadend/tvheadend/blob/release/4.0/src/dvr/dvr_db.c#L1163

Is your server OS 64 or 32-bit?

**Comment by ksooo** [comment] 2016-02-29 23:12
OpenELEC x86_64 - sizeof(time_t) is 8 bytes - checked with a small test program.

Imo, changing https://github.com/tvheadend/tvheadend/blob/release/4.0/src/dvr/dvr_db.c#L1163 to <code>de->de_stop + dvr_entry_get_retention(de) * (time_t)86400</code>, like already in master (https://github.com/tvheadend/tvheadend/blob/master/src/dvr/dvr_db.c#L417) should do the trick.

This could be fixed for tvh 4.0.9 (if this ever will be released) and we somehow would need to teach our users that they will need 4.0.9 in order to get "forever" working and that  otherwise "forever" would behave like "never". At least a remark in the addon default settings would be needed, like we already do with "until disk space needed".

**Comment by Jalle19** [comment] 2016-03-01 08:00
Casting to time_t would just fix overflow issues on 64-bit platforms I think?

**Comment by ksooo** [comment] 2016-03-01 08:17
Indeed. That's right. For 32 bit platforms we need another fix. Please note that wrt this tvh 4.1 is also broken.

**Comment by Glenn-1990** [comment] 2016-03-01 09:53
@ksooo, yes tvh on 32-bit will also have this issue, the only difference is that we never trigger it.
But it should be fixed anyway.

@perexg Does it make sense to fix this overflow in a 4.0.9?

**Comment by Jalle19** [comment] 2016-03-01 13:38
I think the API would need to change to allow for e.g. -1 to indicate "forever".

**Comment by Glenn-1990** [comment] 2016-03-01 13:44
@Jalle19 that was implemented first, but @perexg suggested to only use unsigned ints.
Also we would still have a problem as "until space needed" = max-1

I would prefer to handle overflows as "never delete".

**Comment by perexg** [comment] 2016-03-01 13:56
The problem is not if forever is -1 or 0x7fffffff (INT32_MAX), the problem is 32-bit (time_t)now + days * 86400 . The overflow checks are required in the code for both 4.0 and 4.1.

**Closed** 2016-03-15 08:16 UTC
Labels: Bug
