### ISSUE TITLE
Async Fetch Crash

### ISSUE THREAD

**Issue by vindicatorr** [kodi-pvr/pvr.hts#354] opened 2018-01-25 12:56 UTC
It occurred when I went to view the tv recorded listing while it was fetching the data.
crashlog:
```
...
06:44:52.930 T:139940791300864  NOTICE: Running the application...
06:44:52.944 T:139940791300864  NOTICE: starting zeroconf publishing
06:44:52.944 T:139940791300864  NOTICE: CWebServer[8080]: Started
06:44:55.679 T:139938597230336  NOTICE: PVR Manager: Starting
06:44:56.495 T:139939463919360   ERROR: GetDirectory - Error getting
06:44:57.883 T:139938378262272   ERROR: CPVRTimerInfoTag: no epg tag given for epg based timer type (4)!
06:44:57.926 T:139938378262272   ERROR: Previous line repeats 18 times.
06:44:57.926 T:139938378262272  NOTICE: PVR Manager: Started
06:44:57.928 T:139938378262272   ERROR: CPVRTimerInfoTag: no epg tag given for epg based timer type (4)!
```
journal:
```
systemd-coredump[22199]: Process 22154 (kodi-x11) of user 1000 dumped core.
                                                
                                                Stack trace of thread 22190:
                                                #0  0x00007f4675afc860 raise (libc.so.6)
                                                #1  0x00007f4675afdec9 abort (libc.so.6)
                                                #2  0x00007f4675af50bc __assert_fail_base (libc.so.6)
                                                #3  0x00007f4675af5133 __assert_fail (libc.so.6)
                                                #4  0x00007f4680ee39c0 __pthread_mutex_lock_full (libpthread.so.0)
                                                #5  0x0000563249ef36e8 _ZNK3PVR7CPVREpg19GetTagByBroadcastIdEj (kodi-x11)
                                                #6  0x0000563249eed97b _ZNK3PVR16CPVREpgContainer10GetTagByIdERKSt10shared_ptrINS_11CPVRChannelEEj (kodi-x11)
                                                #7  0x0000563249ee1486 _ZN3PVR14CPVRRecordings16UpdateFromClientERKSt10shared_ptrINS_13CPVRRecordingEE (kodi-x11)
                                                #8  0x0000563249cc28b4 _ZN3PVR10CPVRClient27cb_transfer_recording_entryEPvP19ADDON_HANDLE_STRUCTPK13PVR_RECORDING (kodi-x11)
                                                #9  0x00007f45f3069245 n/a (/home/user/.kodi/addons/pvr.hts/pvr.hts.so.4.2.12)
                                                #10 0x00007f4614121070 n/a (n/a)
                                                #11 0x00007f4614132770 n/a (n/a)
```

As an aside, I'm not sure if my submission of https://trac.kodi.tv/ticket/17745 is applicable to the pvr as well. I can create the ticket here if you think it is.

**Comment by ksooo** [comment] 2018-01-25 13:11
I need the stacks for all threads, otherwise the report is of no value. The ERRORs in the log are not related to the crash (which seems actually to be an ABORT due to a deadlock). And, this is definitely no pvr.hts issue, but a kodi issue.

**Comment by ksooo** [comment] 2018-01-25 13:12
> As an aside, I'm not sure if my submission of https://trac.kodi.tv/ticket/17745 is applicable to the pvr as well. I can create the ticket here if you think it is.

 Not a pvr.hts issue, but same problem with the report - without stack traces I can do nothing about it as I'm not able to reproduce.

**Comment by vindicatorr** [comment] 2018-01-25 13:43
'k, figured out to use coredumpctl gdb # to get the total stack trace (similar to what I also just did in trac):
```
Thread 27 (Thread 0x7f468127b300 (LWP 22154)):
#0  0x00007f4680eea71c in __lll_lock_wait () from /usr/lib/libpthread.so.0
#1  0x00007f4680ee3aa6 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
#2  0x00007f45f30665fa in CTvheadend::GetPlayPosition(PVR_RECORDING const&) () from /home/user/.kodi/addons/pvr.hts/pvr.hts.so.4.2.12
#3  0x0000563249cba31f in ?? ()
#4  0x0000563249cb9182 in ?? ()
#5  0x0000563249cbbcf4 in PVR::CPVRClient::GetRecordingLastPlayedPosition(PVR::CPVRRecording const&, int&) ()
#6  0x0000563249f627c9 in PVR::CPVRClients::ForCreatedClient(char const*, int, std::function<PVR_ERROR (std::shared_ptr<PVR::CPVRClient> const&)>) const ()
#7  0x0000563249f635a9 in PVR::CPVRClients::GetRecordingLastPlayedPosition(PVR::CPVRRecording const&) ()
#8  0x0000563249edd491 in PVR::CPVRRecording::GetResumePoint() const ()
#9  0x0000563249d783de in CGUIInfoManager::GetItemBool(CGUIListItem const*, int) const ()
#10 0x0000563249d92684 in CGUIInfoManager::GetBool(int, int, CGUIListItem const*) ()
#11 0x000056324a17e489 in INFO::InfoSingle::Update(CGUIListItem const*) ()
#12 0x000056324a181f0c in INFO::CSkinVariableString::GetValue[abi:cxx11](bool, CGUIListItem const*) ()
#13 0x0000563249d8917a in CGUIInfoManager::GetItemImage(CFileItem const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ()
#14 0x0000563249ab6e89 in CGUIInfoLabel::GetItemLabel(CGUIListItem const*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const ()
#15 0x0000563249aa9b42 in CGUIImage::UpdateInfo(CGUIListItem const*) ()
#16 0x0000563249ac5473 in CGUIListGroup::UpdateInfo(CGUIListItem const*) ()
#17 0x0000563249acba2d in CGUIListItemLayout::Process(CGUIListItem*, int, unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()
#18 0x0000563249a5a3af in CGUIBaseContainer::ProcessItem(float, float, std::shared_ptr<CGUIListItem>&, bool, unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()
#19 0x0000563249a5e980 in CGUIBaseContainer::Process(unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()
#20 0x0000563249a6b79c in CGUIControl::DoProcess(unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()
#21 0x0000563249a56f4e in CGUIBaseContainer::DoProcess(unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()
#22 0x0000563249a7b345 in CGUIControlGroup::Process(unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()
#23 0x0000563249a6b79c in CGUIControl::DoProcess(unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()
#24 0x0000563249a7b345 in CGUIControlGroup::Process(unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()
#25 0x0000563249a6b79c in CGUIControl::DoProcess(unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()
#26 0x0000563249a7b345 in CGUIControlGroup::Process(unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()
#27 0x0000563249a6b79c in CGUIControl::DoProcess(unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()
#28 0x0000563249b11c69 in CGUIWindow::DoProcess(unsigned int, std::vector<CDirtyRegion, std::allocator<CDirtyRegion> >&) ()
#29 0x0000563249b17aa6 in CGUIWindowManager::Process(unsigned int) ()
#30 0x0000563249d290f7 in CApplication::FrameMove(bool, bool) ()
#31 0x0000563249deeb96 in CXBApplicationEx::Run(CAppParamParser const&) ()
#32 0x00005632499d01bb in XBMC_Run ()
#33 0x000056324936887d in main ()

Thread 26 (Thread 0x7f45ff7fe700 (LWP 22179)):
#0  0x00007f4675bb5753 in select () from /usr/lib/libc.so.6
#1  0x00007f467a2bd53f in ?? () from /usr/lib/libmicrohttpd.so.12
#2  0x00007f467a2bd755 in ?? () from /usr/lib/libmicrohttpd.so.12
#3  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 25 (Thread 0x7f461b7fe700 (LWP 22172)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x0000563249fd85ac in PERIPHERALS::CPeripheralBus::Process() ()
#2  0x000056324998fa15 in CThread::Action() ()
#3  0x000056324998fc88 in CThread::staticThread(void*) ()
#4  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 24 (Thread 0x7f465d327700 (LWP 22161)):
#0  0x00007f4680ee739d in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f4678b51d89 in pa_threaded_mainloop_wait () from /usr/lib/libpulse.so.0
#2  0x000056324a364294 in CAESinkPULSE::AddPackets(unsigned char**, unsigned int, unsigned int) ()
#3  0x000056324a342f1a in ActiveAE::CActiveAESink::OutputSamples(ActiveAE::CSampleBuffer*) ()
#4  0x000056324a3446f2 in ActiveAE::CActiveAESink::StateMachine(int, Actor::Protocol*, Actor::Message*) ()
#5  0x000056324a345427 in ActiveAE::CActiveAESink::Process() ()
#6  0x000056324998fa15 in CThread::Action() ()
#7  0x000056324998fc88 in CThread::staticThread(void*) ()
#8  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 23 (Thread 0x7f45d3fff700 (LWP 22196)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000056324998f8f5 in CThread::Sleep(unsigned int) ()
#2  0x0000563249fa2822 in PVR::CPVRGUIProgressHandler::Process() ()
#3  0x000056324998fa15 in CThread::Action() ()
#4  0x000056324998fc88 in CThread::staticThread(void*) ()
#5  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 22 (Thread 0x7f45f21c0700 (LWP 22188)):
#0  0x00007f4680eeadea in recv () from /usr/lib/libpthread.so.0
#1  0x00007f45f3085fdb in tvheadend::HTSPConnection::ReadMessage() () from /home/user/.kodi/addons/pvr.hts/pvr.hts.so.4.2.12
#2  0x00007f45f3087a8e in tvheadend::HTSPConnection::Process() () from /home/user/.kodi/addons/pvr.hts/pvr.hts.so.4.2.12
#3  0x00007f45f3075f4e in P8PLATFORM::CThread::ThreadHandler(void*) () from /home/user/.kodi/addons/pvr.hts/pvr.hts.so.4.2.12
#4  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 21 (Thread 0x7f45fe60d700 (LWP 22181)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00005632498f3c12 in CJobManager::GetNextJob(CJobWorker const*) ()
#2  0x00005632498f3dca in CJobWorker::Process() ()
#3  0x000056324998fa15 in CThread::Action() ()
#4  0x000056324998fc88 in CThread::staticThread(void*) ()
#5  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 20 (Thread 0x7f45f29c1700 (LWP 22187)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f45f3064f8b in P8PLATFORM::CCondition<bool>::Wait(P8PLATFORM::CMutex&, bool (*)(void*), void*, unsigned int) [clone .constprop.634] () from /home/user/.kodi/addons/pvr.hts/pvr.hts.so.4.2.12
#2  0x00007f45f307518b in CTvheadend::Process() () from /home/user/.kodi/addons/pvr.hts/pvr.hts.so.4.2.12
#3  0x00007f45f3075f4e in P8PLATFORM::CThread::ThreadHandler(void*) () from /home/user/.kodi/addons/pvr.hts/pvr.hts.so.4.2.12
#4  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 19 (Thread 0x7f4618ff9700 (LWP 22177)):
#0  0x00007f4675bb391b in poll () from /usr/lib/libc.so.6
#1  0x00007f467ada8a9c in ?? () from /usr/lib/libavahi-common.so.3
#2  0x00007f467ada8641 in avahi_simple_poll_run () from /usr/lib/libavahi-common.so.3
#3  0x00007f467ada8819 in avahi_simple_poll_iterate () from /usr/lib/libavahi-common.so.3
#4  0x00007f467ada8a34 in avahi_simple_poll_loop () from /usr/lib/libavahi-common.so.3
#5  0x00007f467ada8afb in ?? () from /usr/lib/libavahi-common.so.3
#6  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 18 (Thread 0x7f461affd700 (LWP 22173)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x0000563249fd85ac in PERIPHERALS::CPeripheralBus::Process() ()
#2  0x000056324998fa15 in CThread::Action() ()
#3  0x000056324998fc88 in CThread::staticThread(void*) ()
#4  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 17 (Thread 0x7f461a7fc700 (LWP 22174)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x0000563249feaf82 in PERIPHERALS::CEventScanner::Process() ()
#2  0x000056324998fa15 in CThread::Action() ()
#3  0x000056324998fc88 in CThread::staticThread(void*) ()
#4  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 16 (Thread 0x7f461bfff700 (LWP 22171)):
#0  0x00007f4675bb391b in poll () from /usr/lib/libc.so.6
#1  0x0000563249603022 in PERIPHERALS::CPeripheralBusUSB::WaitForUpdate() ()
#2  0x0000563249603138 in PERIPHERALS::CPeripheralBusUSB::Process() ()
#3  0x000056324998fa15 in CThread::Action() ()
#4  0x000056324998fc88 in CThread::staticThread(void*) ()
#5  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 15 (Thread 0x7f4621a2c700 (LWP 22169)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00005632498f3c12 in CJobManager::GetNextJob(CJobWorker const*) ()
#2  0x00005632498f3dca in CJobWorker::Process() ()
#3  0x000056324998fa15 in CThread::Action() ()
#4  0x000056324998fc88 in CThread::staticThread(void*) ()
#5  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 14 (Thread 0x7f4620b28700 (LWP 22170)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f4620d67ee4 in CEC::CCECClient::Process() () from /usr/lib/libcec.so.4
#2  0x00007f4620d6d1bb in P8PLATFORM::CThread::ThreadHandler(void*) () from /usr/lib/libcec.so.4
#3  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 13 (Thread 0x7f4681239700 (LWP 22166)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000056324998f8f5 in CThread::Sleep(unsigned int) ()
#2  0x000056324999c87c in MEDIA_DETECT::CDetectDVDMedia::Process() ()
#3  0x000056324998fa15 in CThread::Action() ()
#4  0x000056324998fc88 in CThread::staticThread(void*) ()
#5  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 12 (Thread 0x7f463179a700 (LWP 22167)):
#0  0x00007f4675b8bb10 in nanosleep () from /usr/lib/libc.so.6
#1  0x00007f4675bb6064 in usleep () from /usr/lib/libc.so.6
#2  0x00005632495b0a86 in XBMCAddon::xbmc::sleep(long) ()
#3  0x0000563249545752 in ?? ()
#4  0x00007f46783b7449 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#5  0x00007f4678416886 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#6  0x00007f467842c05a in PyEval_EvalCode () from /usr/lib/libpython2.7.so.1.0
#7  0x00007f46784337f1 in run_mod () from /usr/lib/libpython2.7.so.1.0
#8  0x00007f46784350d5 in PyRun_FileExFlags () from /usr/lib/libpython2.7.so.1.0
#9  0x0000563249575775 in CPythonInvoker::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#10 0x00005632495777b0 in CPythonInvoker::Execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#11 0x000056324998fa15 in CThread::Action() ()
#12 0x000056324998fc88 in CThread::staticThread(void*) ()
#13 0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#14 0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 11 (Thread 0x7f4632097700 (LWP 22165)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00005632498f3c12 in CJobManager::GetNextJob(CJobWorker const*) ()
#2  0x00005632498f3dca in CJobWorker::Process() ()
#3  0x000056324998fa15 in CThread::Action() ()
#4  0x000056324998fc88 in CThread::staticThread(void*) ()
#5  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 10 (Thread 0x7f462222d700 (LWP 22168)):
#0  0x00007f4680ee33ca in __pthread_mutex_lock_full () from /usr/lib/libpthread.so.0
#1  0x0000563249ee02f5 in PVR::CPVRRecordings::GetRecordingForEpgTag(std::shared_ptr<PVR::CPVREpgInfoTag> const&) const ()
#2  0x0000563249ef6c65 in PVR::CPVREpg::AddEntry(PVR::CPVREpgInfoTag const&) ()
#3  0x0000563249f0095c in PVR::CPVREpgDatabase::Get(PVR::CPVREpg&) ()
#4  0x0000563249ef4510 in PVR::CPVREpg::Load() ()
#5  0x0000563249eec858 in PVR::CPVREpgContainer::LoadFromDB() ()
#6  0x0000563249ef23d6 in PVR::CPVREpgContainerStartJob::DoWork() ()
#7  0x00005632498f3da9 in CJobWorker::Process() ()
#8  0x000056324998fa15 in CThread::Action() ()
#9  0x000056324998fc88 in CThread::staticThread(void*) ()
#10 0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#11 0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 9 (Thread 0x7f46197fa700 (LWP 22176)):
#0  0x00007f467839d0e7 in collect.lto_priv () from /usr/lib/libpython2.7.so.1.0
#1  0x00007f467843b01a in gc_collect () from /usr/lib/libpython2.7.so.1.0
#2  0x00007f46783b7449 in PyEval_EvalFrameEx () from /usr/lib/libpython2.7.so.1.0
#3  0x00007f4678416886 in PyEval_EvalCodeEx () from /usr/lib/libpython2.7.so.1.0
#4  0x00007f467842c05a in PyEval_EvalCode () from /usr/lib/libpython2.7.so.1.0
#5  0x00007f46784337f1 in run_mod () from /usr/lib/libpython2.7.so.1.0
#6  0x00007f4678435588 in PyRun_StringFlags () from /usr/lib/libpython2.7.so.1.0
#7  0x00007f46784355ef in PyRun_SimpleStringFlags () from /usr/lib/libpython2.7.so.1.0
#8  0x000056324957649e in CPythonInvoker::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#9  0x00005632495777b0 in CPythonInvoker::Execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#10 0x000056324998fa15 in CThread::Action() ()
#11 0x000056324998fc88 in CThread::staticThread(void*) ()
#12 0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#13 0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 8 (Thread 0x7f465cb26700 (LWP 22163)):
#0  0x00007f4675bb391b in poll () from /usr/lib/libc.so.6
#1  0x00007f4678b51773 in ?? () from /usr/lib/libpulse.so.0
#2  0x00007f4678b42bd0 in pa_mainloop_poll () from /usr/lib/libpulse.so.0
#3  0x00007f4678b43271 in pa_mainloop_iterate () from /usr/lib/libpulse.so.0
#4  0x00007f4678b43301 in pa_mainloop_run () from /usr/lib/libpulse.so.0
#5  0x00007f4678b516ae in ?? () from /usr/lib/libpulse.so.0
#6  0x00007f466da6881c in ?? () from /usr/lib/pulseaudio/libpulsecommon-11.1.so
#7  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 7 (Thread 0x7f45f3ab7700 (LWP 22195)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000056324998f8f5 in CThread::Sleep(unsigned int) ()
#2  0x0000563249f76096 in PVR::CPVRGUIInfo::Process() ()
#3  0x000056324998fa15 in CThread::Action() ()
#4  0x000056324998fc88 in CThread::staticThread(void*) ()
#5  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 6 (Thread 0x7f4619ffb700 (LWP 22175)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000056324998ffc8 in CTimer::Process() ()
#2  0x000056324998fa15 in CThread::Action() ()
#3  0x000056324998fc88 in CThread::staticThread(void*) ()
#4  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7f465e329700 (LWP 22159)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000056324998d078 in XbmcThreads::CEventGroup::wait(unsigned int) ()
#2  0x00005632496186c4 in ?? ()
#3  0x000056324998fa15 in CThread::Action() ()
#4  0x000056324998fc88 in CThread::staticThread(void*) ()
#5  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7f465a329700 (LWP 22158)):
#0  0x00007f4680ee739d in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000056324a1b50c1 in ANNOUNCEMENT::CAnnouncementManager::Process() ()
#2  0x000056324998fa15 in CThread::Action() ()
#3  0x000056324998fc88 in CThread::staticThread(void*) ()
#4  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7f465db28700 (LWP 22160)):
#0  0x00007f4680ee7766 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000056324a33a888 in ActiveAE::CActiveAE::Process() ()
#2  0x000056324998fa15 in CThread::Action() ()
#3  0x000056324998fc88 in CThread::staticThread(void*) ()
#4  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7f45fffff700 (LWP 22178)):
#0  0x00007f4675bb5753 in select () from /usr/lib/libc.so.6
#1  0x00007f467a2bd53f in ?? () from /usr/lib/libmicrohttpd.so.12
#2  0x00007f467a2bd755 in ?? () from /usr/lib/libmicrohttpd.so.12
#3  0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7f45f153a700 (LWP 22190)):
#0  0x00007f4675afc860 in raise () from /usr/lib/libc.so.6
#1  0x00007f4675afdec9 in abort () from /usr/lib/libc.so.6
#2  0x00007f4675af50bc in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007f4675af5133 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00007f4680ee39c0 in __pthread_mutex_lock_full () from /usr/lib/libpthread.so.0
#5  0x0000563249ef36e8 in PVR::CPVREpg::GetTagByBroadcastId(unsigned int) const ()
#6  0x0000563249eed97b in PVR::CPVREpgContainer::GetTagById(std::shared_ptr<PVR::CPVRChannel> const&, unsigned int) const ()
#7  0x0000563249ee1486 in PVR::CPVRRecordings::UpdateFromClient(std::shared_ptr<PVR::CPVRRecording> const&) ()
#8  0x0000563249cc28b4 in PVR::CPVRClient::cb_transfer_recording_entry(void*, ADDON_HANDLE_STRUCT*, PVR_RECORDING const*) ()
#9  0x00007f45f3069245 in CTvheadend::GetRecordings(ADDON_HANDLE_STRUCT*) () from /home/user/.kodi/addons/pvr.hts/pvr.hts.so.4.2.12
#10 0x0000563249cb77e2 in ?? ()
#11 0x0000563249cb9182 in ?? ()
#12 0x0000563249cbb65e in PVR::CPVRClient::GetRecordings(PVR::CPVRRecordings*, bool) ()
#13 0x0000563249f67019 in PVR::CPVRClients::ForCreatedClients(char const*, std::function<PVR_ERROR (std::shared_ptr<PVR::CPVRClient> const&)>, std::vector<int, std::allocator<int> >&) const ()
#14 0x0000563249f67518 in PVR::CPVRClients::ForCreatedClients(char const*, std::function<PVR_ERROR (std::shared_ptr<PVR::CPVRClient> const&)>) const ()
#15 0x0000563249f677eb in PVR::CPVRClients::GetRecordings(PVR::CPVRRecordings*, bool) ()
#16 0x0000563249ee0e4b in PVR::CPVRRecordings::UpdateFromClients() ()
#17 0x0000563249ee10b6 in PVR::CPVRRecordings::Update() ()
#18 0x0000563249f9ecce in PVR::CPVRRecordingsUpdateJob::DoWork() ()
#19 0x0000563249f77d67 in PVR::CPVRManagerJobQueue::ExecutePendingJobs() ()
#20 0x0000563249f7980e in PVR::CPVRManager::Process() ()
#21 0x000056324998fa15 in CThread::Action() ()
#22 0x000056324998fc88 in CThread::staticThread(void*) ()
#23 0x00007f4680ee108c in start_thread () from /usr/lib/libpthread.so.0
#24 0x00007f4675bbde1f in clone () from /usr/lib/libc.so.6
```

This is still something you feel I should be submitting to trac instead?

**Comment by ksooo** [comment] 2018-01-25 15:52
> This is still something you feel I should be submitting to trac instead?

Sure, this is a kodi (PVR component) issue.

**Comment by ksooo** [comment] 2018-01-25 18:43
This can be closed as you submitted https://trac.kodi.tv/ticket/17748

**Closed by ksooo** 2018-01-25 18:43 UTC
