### ISSUE TITLE
Forward/backward skips often go to random places or start of recording

### ISSUE THREAD

**Issue by tv21** [kodi-pvr/pvr.hts#92] opened 2015-08-18 21:33 UTC
It appears that in Kodi 15.1, if you try to use the right or left arrow keys on an MCE compatible remote to skip forwards or backwards, it works as you'd expect sometimes but other times takes you to a random place in the program, often in the opposite direction of where you wanted to go.  For example you try to skip backward, and instead it skips forward several minutes.  Sometimes it will take you to the very beginning or very end of the recording.  Sometimes it goes in the direction you want but much further than you wanted.  There is no discernable pattern, it seems totally random.  This only happens in the PVR add-on.  If I copy the recording from the TVHeadEnd server and place it in my Videos directory on the Kodi machine and play it as a Video, then skips work as they are supposed to.  There are no issues with skipping when playing any other type of video.  This is on a Linux-based system running Kodi 15.1 although the problem was also observed in 15.0, but seems even worse since 15.1 came out.

**Comment by sdt** [comment] 2015-08-19 00:07
I'm also getting this behaviour. I've got the new 15.x adaptive-seeking turned off. 

My setup is like this http://kodi.wiki/view/Skip_steps#Instant_skipping with -10s +30s and no delay.

I'm running Ubuntu 15.04 with:
kodi 2:15.1~git20150816.1137-final-0vivid
kodi-pvr-hts 2.1.17-1~vivid
tvheadend v4.0.5

**Comment by Jalle19** [comment] 2015-08-19 06:01
Could any of you please provide a debug log and highlight at which point the bad skip happens?

**Comment by Jalle19** [comment] 2015-08-19 06:02
Reference (was closed as an addon bug): trac.kodi.tv/ticket/16199

**Comment by sdt** [comment] 2015-08-20 00:32
Sorry I didn't get a chance last night. I'll grab some logs tonight.

Do you want any component-specific logging enabled? (I don't know if those add or remove information)

(FWIW, as per the trac ticket, this started happening for me on the 14.x -> 15.x update when I got the new pvr plugin)

**Comment by Jalle19** [comment] 2015-08-20 06:53
Nah, a basic debug log should do the trick.

**Comment by sdt** [comment] 2015-08-20 11:10
https://gist.github.com/sdt/bfac4401387da853f743

Took a little while to repro it - I was starting to fear it was a heisenbug.

Both logs have some comments preceeded by a blank line and then ###

The first log has the jump-forward-while-seeking-backward behaviour.
The second has the jump-back-while-seeking-forwards.

In both cases I hit the button, see where it has seeked to, work out where it should be next, then hit the button again and so on. Fairly rapid succession, but not hitting the button in the middle of a seek.

**Comment by roswellgrey** [comment] 2015-08-21 07:57
Hope that the following is a useful extract of the debug log showing a "jump back to start of recording" example. When it  goes wrong, the "seek to" timecode goes negative and hence playback starts again from the beginning of the file.

https://gist.github.com/roswellgrey/28673b359d94c3c17026

**Comment by Jalle19** [comment] 2015-08-21 14:24
@perexg do you think this could be a tvheadend issue or is it definitely something in the addon? The same type of negative seek is what causes playback to jump to the beginning when skipping in the timeshift buffer.

**Comment by tv21** [comment] 2015-08-21 17:48
I will just note that there are four different frontends connecting to my TVHeadEnd backend.  One is still running XBMC Gotham, one is running Kodi Helix under Ubuntu, one is Kodi Helix on a Mac desktop, and then there is the new one running Kodi Isengard under Ubuntu.  ONLY the new one has this problem - the one running XBMC and the two running Kodi Helix have no issues with skips.  And the new one has no problems with skips if I access the .ts file directly via the Videos menu (without going through the PVR addon).  The only common denominator that I see is the PVR addon that is used if you go to "Live TV" and then try to play the recording from the "Recordings" submenu, but only in Kodi Isengard, and possibly only if you are using Ubuntu as your O.S.

**Comment by roswellgrey** [comment] 2015-08-21 18:24
To add to the above - likewise, I only experienced this when upgrading to Kodi Isengard (from helix), and similarly have no issues at all with accessing the ts container via "Videos" ....   however ... my Kodi clients are Win 7 - in my case, it is not unique to a Ubuntu/Linux client  ...

**Comment by cotman** [comment] 2015-08-21 21:05
Further bit of context, for Linux and tvheadend 4.0.5:

I experience exactly what's here with OpenElec 5.95.3 and pvr.hts 2.1.16 and, on Ubuntu 14.04, with Kodi 16.0-ALPHA2 Git:0aa0ee7 and pvr.hts 2.2.5.

**Comment by beralt** [comment] 2015-08-23 17:06
I can confirm that this behavior is only appearing after an upgrade of Kodi to version 15 and above. Since the new seeking was implemented I'm able to seek much further (and faster) in the buffer than before, and it is at that point that the seeking becomes erratic. My point is that the bug might have been there before the upgrade, and that I'm just experiencing it with by seeking further than I used to.

**Comment by roswellgrey** [comment] 2015-08-26 08:29
Another example where previous GENERAL_RESYNC goes negative and causes erroneous "seek to" time (although in this case the "seek to" time didn't go negative - it just caused a large leap backwards)

https://gist.github.com/roswellgrey/2935147856a605af27d3

As I can (infrequently) reproduce this with my setup, I would be more than willing to, for example, run a custom build with more debugging added if it would help ...

**Comment by FernetMenta** [comment] 2015-08-26 08:38
As I implemented timeshift for vnsi I has a similar issue. An old demux packet in the queue messed up timestamps. Now I tag demux packets with a serial that is changed on every seek. Packets with a serial that does not match are discarded. Maybe that helps:
https://github.com/kodi-pvr/pvr.vdr.vnsi/commit/b6dba48891d2877a68e65aab529b036eef90e5ca

**Comment by Glenn-1990** [comment] 2015-08-27 22:02
@Jalle19 
Maybe we need a  'm_buffer.reset()' and 'm_bHasData = false' before the seek too, so no older packets can sneak in while tvheadend is progressing the seek?
so here: https://github.com/kodi-pvr/pvr.hts/blob/master/src/HTSPVFS.cpp#L181

I bet it goes wrong somewhere here if we indeed have older packets as @FernetMenta suggested:
https://github.com/kodi-pvr/pvr.hts/blob/master/src/HTSPVFS.cpp#L168
After a seek, the buffer is empty, so we are waiting on this condition, but if we are skipping again now, we can get old packets as the buffer is only reset when the complete seek is done? Just an assumption, I've no way to test this now.

**Comment by joepadmiraal** [comment] 2015-09-04 19:29
I am also having this issue on a fresh Kodibuntu installation and on a macbook. Both with Kodi 15.1. So definitively not an OS specific issue.

**Comment by cotman** [comment] 2015-09-06 07:35
I know this is now an official bug, but it's kinda unclear from the history whether it's "dev reproducible".

Is it a replicatable "thing" from a developer perspective now, or is there something us users can still help with to get it to that point?

**Comment by BoxFreak** [comment] 2015-09-06 10:52
I'm experiencing this too with Openelec 5.0.8 (which is Helix). My tvheadend client is version 1.9.40.

**Comment by Jalle19** [comment] 2015-09-07 08:45
@BoxFreak are you sure it's the same bug? All others say this is a regression and that it used to work in Helix.

**Comment by Jalle19** [comment] 2015-09-07 08:46
@Glenn-1990 I think you and @FernetMenta are right, that's probably where things go wrong. I haven't had any time to work on Kodi for a while unfortunately.

**Comment by BoxFreak** [comment] 2015-09-07 09:00
@Jalle19 Yes I think. Recently I've only encountered it with timeshift -buffer because I haven't used my system for recording because of general unreliability. I can test recordings too if it's necessary and makes any difference.

**Comment by Jalle19** [comment] 2015-09-07 10:37
The timeshift buffer and recordings are two very separate things from a code perspective so it's unlikely that the issues are related.

**Comment by BoxFreak** [comment] 2015-09-07 17:32
OK, just tested playing back recording, and it works just fine. So problem is only with timeshiftbuffer. Sorry about this confusion.

**Comment by tv21** [comment] 2015-09-08 18:57
Jalle19, according to this page https://github.com/Jalle19 you've had time to push 26 separate commits to four different projects (besides this one) between September 2 and September 4.  I don't know what pushing a commit entails but I really wish you could find a few minutes to devote to fixing this issue, because it is EXTREMELY annoying to everyone who is experiencing it.  I don't know how grateful people are when you work on those other projects, but we'd all be extremely grateful if you'd fix this particular bug before the new fall TV season starts in earnest.

**Comment by bas-t** [comment] 2015-09-08 19:02
@tv21 I get your point, but I just think you should refrase that so it would be a request. As it is, it sounds pushy to me.

**Comment by bluenote73** [comment] 2015-09-08 19:03
@tv21 holy shit, get ahold of your entitlement and back off.  Good grief, I can't even.
No excuse to act like an asshole like this.  VOLUNTEERS doing this work.  Nobody owes you anything.

**Comment by bas-t** [comment] 2015-09-08 19:07
@bluenote73 That's what I ment, but I like to keep my voice a bit down.

**Comment by fritsch** [comment] 2015-09-08 19:08
@tv21 you are extremely annoying to everyone ... you could have picked it and PRd it - but instead you tell here a big story. We owe you nothing, absolutely nothing.

**Comment by FernetMenta** [comment] 2015-09-08 19:34
I hope @Jalle19 gets not too disappointed reading this. @tv21 you'd better terminate your github account.

**Comment by tv21** [comment] 2015-09-08 20:56
fritsch, you seem to look for reasons to be annoyed (why do you even hang around if user comments annoy you so much?) so I wouldn't even respond if it were only you that were annoyed.  To everyone else, though, I apologize if my comment was over the top.  This bug is SUPER annoying and all I was trying to say is that I think we would all be very appreciative if one of the developers could find the time to work on it.  I did not intend to come across as demanding or entitled, after all I know this is free software and we have no right to demand anything, but sometimes I just wonder if the developers that may not be experiencing this bug (for whatever reason) have any idea just how annoying it is.  On a scale of software annoyances, this one's a 10 in my book.  So I just really hope someone's looking at it, or will do so in the near future, because I think we will all be VERY appreciative when it's fixed.

Again, I'm very sorry if my original post came across as rude or demanding, it was not intended to be, but I have been told that sometimes when I write things people who read them won't take them the way I intended, so while I won't go as far as to terminate my github account, I won't make any further posts here.

**Comment by fritsch** [comment] 2015-09-08 20:58
>fritsch, you seem to look for reasons to be annoyed (why do you even hang around if user comments annoy you so much?)

Yeah, good question. When I read your comments I don't really know why I waste my free time to write free software for you. And if you did not get it - everybody that is subscribed to this repository gets automatically emailed with every comment - so basically it was not my choice to read your comment ...

**Comment by bas-t** [comment] 2015-09-08 21:29
I'm confused. It was just a comment???

**Comment by cotman** [comment] 2015-09-09 12:39
Annyhoo ;)

As-per my comment earlier: is this considered a known, reproducible, issue now (little hard to tell from the responses) i.e. is there anything we can do, user-side, to help with more information, debug logs etc when we see it happens?

**Comment by Marty56** [comment] 2015-09-12 03:40
This bug seem to be existing in all versions of Kodi 15.2
I can confirm that I am experiencing it under FireTV(Android), Mac OS (Yosemite) and Windows 10.

**Comment by speedyrazor** [comment] 2015-09-15 05:53
I have Ubuntu 14.04, TVHeadend 4.0.5 and Kodi 15.1 and I also have the same issue reported here. I am about to downgrade to Kodi 14.2 to make my system usable.

**Comment by Jalle19** [comment] 2015-09-15 08:48
@cotman yes I can reproduce it from time to time but I haven't been able to track down the root cause yet.

**Comment by cotman** [comment] 2015-09-15 09:04
@Jalle19 Thanks.  It is strange - I saw it a lot, then not so much, but very recently a lot more.

**Comment by speedyrazor** [comment] 2015-09-16 19:07
I can see that still no one is assigned to this ticket. Is someone going to pick this up, please please please...

**Comment by bas-t** [comment] 2015-09-16 20:04
Don't whine whine whine...
if that someone is not you.

Op 16-09-15 om 21:07 schreef speedyrazor:

**Comment by beralt** [comment] 2015-09-17 08:24
@Glenn-1990 I tried your approach to fix this issue by resetting the buffer and invalidating it. It took me a while to get the build system up and running. Unfortunately it seems that the issue persists.

**Comment by Glenn-1990** [comment] 2015-09-17 19:55
@beralt Could you also add this? 
So keep the code you already changed.
https://github.com/Glenn-1990/pvr.hts/commit/4be5911d760383d6e60fab322d2ed7cfe561f1c3

I might be totally wrong here, I don't know much about this part of the code, but it's an attemp ;-)

**Comment by beralt** [comment] 2015-09-18 07:20
@Glenn-1990 That seems to fix the issue. I've tested this a few minutes ago, and I cannot reproduce it.  But I'm a bit worried about the fix itself, since other code paths lead to reset of the buffer too. A more elegant fix would be to invalidate certain packets in the buffer, instead of clearing it out. But I'd rather leave that to the experts.

**Comment by Marty56** [comment] 2015-09-20 15:56
if this fix is included in the V 15.2 RC 2, then it does not work.
Tested it on FireTV Stick.

**Comment by Jalle19** [comment] 2015-09-20 15:58
No fix id included anywhere yet.

**Closed** 2015-09-21 10:23 UTC
Labels: Bug

**Comment by puithove** [comment] 2015-09-21 13:28
Testing what was merged - have only been using it for a short time, but it does appear that I can confirm it resolves the issue for me.  I'll be giving it some more heavy usage later on.  Thanks so much for working on this.

**Comment by speedyrazor** [comment] 2015-09-27 07:09
Looks good, is this going to be committed to master?

**Comment by Jalle19** [comment] 2015-09-27 08:09
It was already.

**Comment by speedyrazor** [comment] 2015-09-27 13:33
Is it in 15.2 or 16?
Im on linux, if I use one of the below will I get that fix uncluded?

ppa:team-xbmc/unstable
ppa:team-xbmc/xbmc-nightly

Kind regards.

**Comment by Jalle19** [comment] 2015-09-27 15:33
Yes.
