### ISSUE TITLE
pass subscription information to KODI

### ISSUE THREAD

**Issue by piotrasd** [kodi-pvr/pvr.hts#310] opened 2017-06-06 18:02 UTC
Hi 
could you make passing information about subscription to KODI to make extended view or add more info in diagnostic information from KODI side

![screenshot078](https://user-images.githubusercontent.com/773012/26844194-8ef1118c-4aea-11e7-847f-58fcbffae079.png)

i saw that information are in htsp

htsmsg_add_u32(m, “pid”, di->pid);
htsmsg_add_u32(m, “caid”, di->caid);
htsmsg_add_u32(m, “provid”, di->provid);
htsmsg_add_u32(m, “ecmtime”, di->ecmtime);
htsmsg_add_u32(m, “hops”, di->hops);
htsmsg_add_str(m, “cardsystem”, di->cardsystem);
htsmsg_add_str(m, “reader”, di->reader);
htsmsg_add_str(m, “from”, di->from);
htsmsg_add_str(m, “protocol”, di->protocol

thx

**Comment by Jalle19** [comment] 2017-06-08 06:59
Duplicate of https://github.com/kodi-pvr/pvr.hts/issues/106

**Closed by Jalle19** 2017-06-08 06:59 UTC
