### ISSUE TITLE
pvr.hts addon reconnection issue to Tvheadend backend after wake-up

### ISSUE THREAD

**Issue by sakos** [kodi-pvr/pvr.hts#235] opened 2016-08-29 17:36 UTC
The setup:
HTPC running on Libreelec 7.0.2 with latest pvr.hts addon. The backend is a Wetek Play box running on Libreelec 7.0.2 with latest Tvheadend addon.
When I switch off the TV the HTPC goes to sleep mode. Switching on the TV wakes up the HTPC. The Live TV is configured to play last viewed channel at startup. 

The symptom:
I would like the HTPC starts playing the last viewed TV channel after waking up. It works fine if the HTPC was sleeping only for a short time, however does not work if it slept for longer time (e.g one day).
This problem is legacy. It has been there for longer time with much older versions of tvheadend and pvr.hts addons.

Recover:
Select any channel manually. 

Findings:
- Tvheadend backend tracks the logged in clients. If there is no activity, Tvheadend removes the inactive clients from the connection list. I found that the symptom described above happenes when the client has been removed form this lis due to inactivity. In this case the firts attempt of reconnection request of pvr.hts client fails. It repeats the connection request however terminates the playback.
  The problem can be reproduced fast if the client is deleted manually from Tvheadend active client list.

Client logs:
`8:30:29 T:140653944363072  NOTICE: PVRManager - ContinueLastChannel - continue playback on channel 'RTL2'
18:30:29 T:140653944363072  NOTICE: PVRManager - StartPlayback - started playback on channel 'RTL2'
18:30:29 T:140653944363072  NOTICE: DVDPlayer: Opening: pvr://channels/tv/Minden csatorna/pvr.hts_1835670083.pvr
18:30:29 T:140653944363072 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:30:29 T:140653459662592  NOTICE: Creating InputStream
18:30:30 T:140651177961216  NOTICE: VideoInfoScanner: Starting scan ..
18:30:33 T:140653459662592   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command subscribe failed: No response received
18:30:33 T:140653459662592   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to write (Invalid argument)
18:30:33 T:140653459662592   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to transmit
18:30:33 T:140653459662592   ERROR: CDVDPlayer::OpenInputStream - error opening [pvr://channels/tv/Minden csatorna/pvr.hts_1835670083.pvr]
18:30:33 T:140653459662592  NOTICE: CDVDPlayer::OnExit()
18:30:33 T:140651112544000   ERROR: PVR - GetEPGForChannel - addon 'Tvheadend:wetek:9982 [connected]' returned an error: the command failed
18:30:33 T:140651112544000   ERROR: PVR - GetEPGForChannel - cannot get EPG for channel 'Motorvision TV' from client '27195': the command failed
18:30:33 T:140651112544000   ERROR: EPG - Update - failed to update table 'Motorvision TV'
18:30:33 T:140653944363072  NOTICE: CDVDPlayer::CloseFile()
18:30:33 T:140653944363072  NOTICE: DVDPlayer: waiting for threads to exit
18:30:33 T:140653944363072  NOTICE: DVDPlayer: finished waiting
18:30:33 T:140653944363072  NOTICE: CDVDPlayer::CloseFile()
18:30:33 T:140653944363072  NOTICE: DVDPlayer: waiting for threads to exit
18:30:33 T:140653944363072  NOTICE: DVDPlayer: finished waiting
18:30:36 T:140651177961216   ERROR: NFS: Failed to mount nfs share:  (nfs_service failed)
18:30:36 T:140651177961216 WARNING: Process directory 'nfs://192.168.10.29/nfs/Public/Videos/Filmek/' does not exist - skipping scan.
18:30:37 T:140651112544000   ERROR: PVR - GetEPGForChannel - addon 'Tvheadend:wetek:9982 [connected]' returned an error: the command failed
18:30:37 T:140651112544000   ERROR: PVR - GetEPGForChannel - cannot get EPG for channel 'M1' from client '27195': the command failed
18:30:37 T:140651112544000   ERROR: EPG - Update - failed to update table 'M1'
18:30:39 T:140651177961216 WARNING: Process directory 'nfs://192.168.10.29/nfs/Public/Videos/Filmek/(1992) Dermesztő szenvedélyek/' does not exist - skipping scan.
18:30:41 T:140651112544000   ERROR: PVR - GetEPGForChannel - addon 'Tvheadend:wetek:9982 [connected]' returned an error: the command failed
18:30:41 T:140651112544000   ERROR: PVR - GetEPGForChannel - cannot get EPG for channel 'B1' from client '27195': the command failed
18:30:41 T:140651112544000   ERROR: EPG - Update - failed to update table 'B1'
18:30:42 T:140651177961216 WARNING: Process directory 'nfs://192.168.10.29/nfs/Public/Videos/Filmek/10.Rules.For.Sleeping.Around.2013.DVDRip.XviD-EXViD/' does not exist - skipping scan.
18:30:45 T:140651177961216 WARNING: Process directory 'nfs://192.168.10.29/nfs/Public/Videos/Filmek/11.parancsolat.2004.DVDRip.Xvid-Atyus/' does not exist - skipping scan.
18:30:48 T:140651177961216 WARNING: Process directory 'nfs://192.168.10.29/nfs/Public/Videos/Filmek/12.Years.a.Slave.2013.720p.BluRay.DD5.1.x264.HuN-MWT/' does not exist - skipping scan.
18:30:51 T:140651177961216 WARNING: Process directory 'nfs://192.168.10.29/nfs/Public/Videos/Filmek/13.Sins.2014.HDRip.H.264.HunSub-TERACOD/' does not exist - skipping scan.
18:30:54 T:140651177961216 WARNING: Process directory 'nfs://192.168.10.29/nfs/Public/Videos/Filmek/2.Guns.2013.720p.BluRay.DTS.x264.HuN-MWT/' does not exist - skipping scan.
18:30:56 T:140653944363072  NOTICE: DVDPlayer: Opening: pvr://channels/tv/Minden csatorna/pvr.hts_1323774088.pvr
`

Server logs:
`2016-08-29 18:32:08.280 [   INFO] htsp: Got connection from 192.168.10.25
2016-08-29 18:32:08.289 [   INFO] htsp: 192.168.10.25: Welcomed client software: Kodi Media Center (HTSPv25)
2016-08-29 18:32:08.296 [   INFO] htsp: 192.168.10.25 [ Kodi Media Center ]: Identified as user 'htpc2'
2016-08-29 18:32:12.277 [   INFO] htsp: 192.168.10.25 [ htpc2 | Kodi Media Center ]: Write error -- Broken pipe
2016-08-29 18:32:13.626 [   INFO] htsp: 192.168.10.25 [ htpc2 | Kodi Media Center ]: Disconnected
2016-08-29 18:32:13.629 [   INFO] htsp: Got connection from 192.168.10.25
2016-08-29 18:32:13.631 [   INFO] htsp: 192.168.10.25: Welcomed client software: Kodi Media Center (HTSPv25)
2016-08-29 18:32:13.634 [   INFO] htsp: 192.168.10.25 [ Kodi Media Center ]: Identified as user 'htpc2'
2016-08-29 18:32:34.879 [   INFO] mpegts: 12111V in Thor 0.8W - tuning on Availink IN2 AVL6211+AV2011 DVB-S/S2 : DVB-S #0
2016-08-29 18:32:35.412 [   INFO] capmt: Oscam pc-nodmx mode: Starting CAPMT server for service "RTL+" on adapter 1
2016-08-29 18:32:35.413 [   INFO] subscription: 8B84: "192.168.10.25 [ htpc2 | Kodi Media Center ]" subscribing on channel "RTL+", weight: 150, adapter: "Availink IN2 AVL6211+AV2011 DVB-S/S2 : DVB-S #0", network: "Thor 0.8W", mux: "12111V", provider: "UPC Direct", service: "RTL+", profile="htsp", hostname="192.168.10.25", username="htpc2", client="Kodi Media Center"`

**Comment by Jalle19** [comment] 2016-08-30 08:16
I've noticed similar things. When I resume from sleep and press a channel, Kodi says "working" for a while and then you get some notifications from the addon (startup stuff like added timers etc.). Playback doesn't start until you press the channel a second time.

**Comment by ksooo** [comment] 2016-08-30 08:24
> I found that the symptom described above happenes when the client has been removed form this lis due to inactivity. In this case the firts attempt of reconnection request of pvr.hts client fails.

 Isn't this a tvheadend issue, then? Not sure, though.

**Comment by ksooo** [comment] 2016-08-30 08:31
@sakos could you please activate kodi debug logging and pvr.hts trace setting and provide a kodi.log with debugging info? Should contain much more info, then.

**Comment by sakos** [comment] 2016-08-30 09:16
@ksooo I will collect the requested logs. Which kodi debug log components are needed?

**Comment by ksooo** [comment] 2016-08-30 11:02
No special Kodi components required, most important is to activate trace for pvr.hts in the settings of the add-on.

Currently I fear that (on wetek) Kodi does not send proper onsleep and onwake events to pvr.hts, but without a log this is just wild guessing.

Do you have the chance to test whether this issue also occurs with a recent Kodi Krypton nightly build? I do remember that there have been fixes for onsleep/onwake in Kodi Krypton. Maybe we're riding a dead horse here because there are no more issues with Krypton...

**Comment by sakos** [comment] 2016-08-31 17:42
Hi,

See the [logfiles](https://drive.google.com/open?id=0B5W_NGHuyu_ubGJaVDdyU0hwQWM). 
(Actually neither the power on looks OK, but disregard it for now)
Is the pvr.hts extra log included? I did not find any specific logfile for the addon.

I will test Librelec 8.0 alpha later. Hope the log helps to understand the root cause.

**Comment by ksooo** [comment] 2016-08-31 18:14
@sakos thanks for the log files. yes, all interesting data are in. Seems, that the subscription to the channel to be continued on wake is done so early that the addon has not yet restored the connection to tvheadend... and weird things happen because of this.

**Comment by Jalle19** [comment] 2016-08-31 20:05
Would be interesting to know if this happens with other backends too or if it's a problem we need to take care of in pvr.hts.

**Comment by ksooo** [comment] 2016-08-31 20:50
I think it's a kodi problem as kodi does not check the connection state before tuning the channel. With krypton and the new connection state change callback this should be easy to implement correctly.

**Comment by sakos** [comment] 2016-10-08 18:40
Hi, tested with Librelec 8.0 alpha (Kodi Krypton) and the same issue is present. I do not know if the change above is included in the latest pvr.hts addon version="3.4.7"

**Comment by Jalle19** [comment] 2016-10-09 18:04
It's not yet merged because I completely forgot to actually runtime test it.

**Comment by ksooo** [comment] 2016-10-09 19:54
Which change?

**Comment by sakos** [comment] 2017-01-03 18:01
Hi,

After upgrading to Libreelec 7.90.010 the pvr.hts addon is updated to 3.4.12. I assume this contains your fix.
Sorry to say but the problem is still present or even worse.
Now, the same conditions causes Kodi to crash. It happens every time.
See crashlog here: http://sprunge.us/TSeC

If I enable debug the crash cannot be reproduced at all, however the TV channel will not start.
See the log here: http://sprunge.us/ZddF
It contains two wake up cycles.

**Comment by sakos** [comment] 2017-01-03 18:01
Accidentally closed. The issue is still present.

**Comment by ksooo** [comment] 2017-01-03 19:42
> Now, the same conditions causes Kodi to crash. It happens every time.
> See crashlog here: http://sprunge.us/TSeC

 It crashes due to a deadlock in kodi. Definitely not a pvr.hts issue. However, I will look into the deadlock problem.

**Comment by Jalle19** [comment] 2017-01-10 13:56
@sakos is this still an issue with the lastest Krypton RC releases?

**Comment by sakos** [comment] 2017-01-10 14:51
Where can I find a Libreelec build containing this fix?

**Comment by Jalle19** [comment] 2017-01-10 19:35
@sakos try http://chewitt.libreelec.tv/testing/8.0/, those are the newest builds I could find

**Comment by Jalle19** [comment] 2017-01-10 19:49
@sakos what platform do you use? x86_64?

**Comment by sakos** [comment] 2017-01-10 19:55
x86_64. The link you sent some minutes ago is not working. 
Do you think the latest Millhouse build good for testing? # Kodi version (18.0-ALPHA1 Git:5c40b5c)
http://forum.kodi.tv/showthread.php?tid=298462&page=19

**Comment by Jalle19** [comment] 2017-01-10 19:56
Yeah I had to remove it. I guess those would work too, please try one of them.

**Comment by sakos** [comment] 2017-01-10 20:01
I will. I am afraid it needs some days.

**Comment by sakos** [comment] 2017-01-13 16:53
Hi,

I did a test with Milhouse's [LibreELEC.tv Leia build #0112](http://forum.kodi.tv/showthread.php?tid=298462&pid=2499620#pid2499620) 
Beside instabilities and inconsistent behaviors, TV reception started fine 4 out of 7 trials. In the remaining 3 cases the video did not start. I could see in Tvheadend backend that the pvr.hts client was connecting to the backend but did not subscribe to a channel.
I managed to capture [Kodi log](https://www.dropbox.com/s/h91hw9zz0uvmrfj/log-2017-01-13-16.33.29.zip?dl=0). The debug logging was enabled around 17:30 then at the next wake up the fault came. Then logging stopped. You should look into the last wake up event in the log.
(Previous trials are also included, but I am not sure if the logs are detailed enough.)

The [backend logs](http://pastebin.com/z7nL546S) covering the test period are also availabe for you. I did not change channel manually. All subscriptions was performed automatically by the client.

**Comment by richardmayer** [comment] 2017-05-18 04:37
Hello, 

after having the exact same problems on my Kodi PC, I found this discussion.
I'm running OpenELEC 8.0.3 x64 on an Intel Skylake NUC and I'm having the exact same problem described here.
Are there any updates on this issue or any workarounds besides having the "Suspend-Mode" disabled?
After finally making the step away from Windows Media Center, this is the only thing bugging me...

Best Regards

Richard

**Comment by sakos** [comment] 2017-05-18 05:53
Richard, I created a simple script in  /storage/.config/sleep.d which starts pvr playing with 10 seconds delay after waking up. It has been there for long time and working fine. Not sure if the original problem is still present at all.

**Comment by Jalle19** [comment] 2017-05-18 11:12
Speaking of this, my dad's LibreELEC 8.0.1 HTPC doesn't have this issue at all, and he suspends it every day. Not sure what the root cause is.

**Comment by richardmayer** [comment] 2017-05-18 15:41
@sakos:
That's funny: I was just about to edit a script to be placed in /storage/.config/sleep.d to restart Kodi on Resume when I read your Reply. Sadly, I cannot get it to work although it seems very simple...
http://openelec.tv/forum/90-miscellaneous/83653-suspend-resume-script-not-working

**Comment by richardmayer** [comment] 2017-05-18 15:54
@Jalle19: 
I'm not sure, what the real problem is.
The original problem described here sounded just like my problem but after more investigation, maybe the whole Kodi Environment is "hanging" a short time after resume for a few seconds...
I will have to do some more research. 
Thanks for your help so far.
Richard

**Comment by CvH** [comment] 2017-05-18 16:09
@richardmayer
Did you use an recent up to date Tvheadend version (4.2...) ? The 2yr old "stable" 4.0 is know to have all kind of random problems. Also make sure that you have all tuners deactivated that have no physical reception. Speaking for LibreELEC there is no known issue with the sleep/wake script. Activating the delayed start for 1-2 sec could help too - depending at the driver they work sometimes better or worse.

**Comment by richardmayer** [comment] 2017-05-18 16:34
I'm running TVHeadend 4.2.2-8~g8ff5aa2 (4.2 stable).
I know the sleep/wake script should work - I'm getting crazy checking everything 10 times - it just will ignore my script.
Do you mean the "Wait for network connections before launch" with the delayed start? Or is there a different option for the delayed start?

**Comment by CvH** [comment] 2017-05-18 16:50
@richardmayer its an shot in the dark (maybe, maybe not)
![image](https://cloud.githubusercontent.com/assets/1355173/26213845/c0eb94d6-3bfa-11e7-8dc8-4d86141321f1.png)

**Comment by richardmayer** [comment] 2017-05-18 17:05
Oh ok - I'm running TVHeadend on a different machine on the same network (always running).
That's why I haven't ever seen this option.

**Comment by sakos** [comment] 2017-05-18 17:24
@CvH,
I also run the Tvheadend server on a different machine. The probelm is with the HTS client. See my first post with explanation.

@richardmayer,
Resume script has been working fine on my systems over different Libreelec versions. I have to use it for other purpose as well, since there is no sound after wake up due to a kernel issue.
try this.

```
#!/bin/sh
case "$1" in
   pre)
#     <do something on suspend>
     ;;
   post)
#     <do something on resume>
       sleep 10
       kodi-send --action"playpvrtv"
     ;;
esac 
```

**Comment by sakos** [comment] 2017-05-18 17:25
accidentally closed

**Comment by CvH** [comment] 2017-05-18 17:30
@sakos sry for the noise, seems i misinterpreted the suspend script ;)

**Comment by richardmayer** [comment] 2017-05-18 18:33
Ok, as for the Suspend/Resume topic, there is one mystery less.
I made a Backup in OpenELEC using the Backup tool, installed LibreELEC on the internal SSD.
Restored the previously made OpenELEC Backup to the fresh LibreELEC installation.
Now it just works as expected.
Will take a look at the PVR behaviour now.
Best Regards
Richard

**Comment by sakos** [comment] 2017-11-27 19:51
Hi,

It seems the problem is still present in Libreelec 8.2.0 (Kodi v17.5 Krypton). It is a bit worse, as now Kodi hangs after unsuccessful re-connection. I neither was able to reproduce the problem by forced removal of client from backend.

```
20:34:58.910 T:139660881909440  NOTICE: OnWake: Running resume jobs
20:34:58.910 T:139660881909440  NOTICE: OnWake: Restarting lirc
20:34:58.910 T:139660793739008 WARNING: CActiveAE::StateMachine - signal: 0 from port: OutputControlPort not handled for state: 6
20:34:59.451 T:139658053949184   ERROR: OpenConnection - could not opening a connection to the CEC adapter
20:34:59.452 T:139660097472256   ERROR: CecLogMessage - could not start CEC communications
20:34:59.955 T:139660122650368  NOTICE: Register - new cec device registered on cec->/dev/ttyACM0: CEC Adapter (2548:1002)
20:35:03.910 T:139660881909440   ERROR: ActiveAE::Resume - failed to init
20:35:03.910 T:139660881909440  NOTICE: UpdateLibraries: Starting video library startup scan
20:35:03.912 T:139660881893120  NOTICE: PVRManager - ContinueLastChannel - continue playback on channel 'RTL Klub HD'
20:35:03.914 T:139660881893120  NOTICE: PVRManager - StartPlayback - started playback on channel 'RTL Klub HD'
20:35:03.937 T:139660881909440  NOTICE: VideoPlayer: Opening: pvr://channels/tv/Minden csatorna/pvr.hts_1487884727.pvr
20:35:03.937 T:139660881909440 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:35:03.938 T:139658209998592  NOTICE: Creating InputStream
20:35:04.445 T:139658070734592  NOTICE: VideoInfoScanner: Starting scan ..
20:35:07.940 T:139658209998592   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command subscribe failed: No response received
20:35:07.940 T:139658209998592   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to write (Invalid argument)
20:35:07.940 T:139658209998592   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to transmit
20:35:07.941 T:139658209998592   ERROR: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/Minden csatorna/pvr.hts_1487884727.pvr]
20:35:07.941 T:139658209998592  NOTICE: CVideoPlayer::OnExit()
20:35:50.529 T:139659602532096  NOTICE: script.tv.show.next.aired: ### starting data update
20:35:59.787 T:139658251962112  NOTICE: ES: Client  from ::ffff:127.0.0.1 timed out


```

**Comment by cdric61** [comment] 2020-05-04 11:10
Hello,

I see exactly the same problem with lastest Kodi version (Leia 18.6) on Android 9.0 (MiBox S).
Tvheadend Server is on a Synology Nas.
Is there a solution ?

**Comment by CvH** [comment] 2020-05-04 15:14
I have the same issue since at least Kodi 17. It is always the first attempt that fails regardless if network is available or not and regardless how much time is passed. Found no workaround for that, it just fails 100% at every try.
This is easily reproduce-able if someone has a patch :)

Kodi19 master
```
17:07:06.040 T:885      INFO <general>: Updated radio channel 'RTL2' in group 'TV channels'
17:07:06.040 T:885      INFO <general>: Updated radio channel 'RTL2' in group 'Ohne HD'
17:07:06.158 T:881      INFO <general>: AddOnLog: Tvheadend HTSP Client: pvr.hts - async updates initialised
17:07:10.934 T:2760    ERROR <general>: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command subscribe failed: No response received
17:07:10.934 T:2760    ERROR <general>: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to write (Invalid argument)
17:07:10.934 T:2760    ERROR <general>: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to transmit
17:07:10.934 T:2760    ERROR <general>: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/Alle%20Kan%c3%a4le/pvr.hts_1833488544.pvr]
17:07:10.934 T:2760     INFO <general>: CVideoPlayer::OnExit()
```

**Comment by cdric61** [comment] 2020-05-05 04:56
It's the same in Kodi 19 ?
I hoped it was solved.
Nobody has a workaround ?

**Comment by sakos** [comment] 2020-05-05 13:50
As the submitter of this ticket let me comment. When I saw the update a day ago I was surprised a bit as I have not been observed the issue for a very long time. Them I realised the explanation. My HTPC was replaced with a small S905x amlogic box two years ago and it never goes to sleep hence maintains the connection. Can be considered as a workaround?

**Comment by cdric61** [comment] 2020-05-05 13:55
Yes, it may be. I have a MiBox S.
How do you maintain the connection ?

**Comment by sakos** [comment] 2020-05-05 14:32
I mean, I do nothing particular. The box does not go sleep mode when I switch of the TV and it seems the TVH client running on the box is always connected to the backend server. No reconnection is needed, no problem is seen.
My only settings in CEC menu the stop playing when TV is switched off. The only drawback of this complete solution that I have to start live TV manually after TV is switched on again. But it can be done by a single press of red button.

**Comment by cdric61** [comment] 2020-05-07 08:29
Ok thanks.
But I don't have this CEC option (stop playing TV when TV is switched off) on my Kodi / MiBox S installation.
So this workaround is not for me.
I will generate log and post it here but I think it will be the same than yours.

**Comment by sakos** [comment] 2020-05-07 10:30
Does not your CEC menu look like this? 
https://forum.libreelec.tv/core/image-proxy/?key=2750c2c7b331743882ab786148edbcb3ae320ea7f7e26c04105f803866c3e74a-aHR0cHM6Ly9pLmltZ3VyLmNvbS9KNDVWb3F4LmpwZw%3D%3D

**Comment by cdric61** [comment] 2020-05-07 11:33
I don't have a CEC menu in Kodi. I know it might be in System/Input but there is nothing.
I'm not sure it works with Android.

**Comment by cdric61** [comment] 2020-05-07 13:39
And the log:

`2020-05-07 15:38:43.015 T:5709  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Toutes les chaînes/pvr.hts_785360369.pvr`
`2020-05-07 15:38:43.022 T:6221  NOTICE: Creating InputStream`
`2020-05-07 15:38:48.025 T:6221   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command subscribe failed: No response received`
`2020-05-07 15:38:48.026 T:6221   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to write (Invalid argument)`
`2020-05-07 15:38:48.027 T:6221   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - failed to transmit`
`2020-05-07 15:38:48.027 T:6221   ERROR: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/Toutes les chaînes/pvr.hts_785360369.pvr]`
`2020-05-07 15:38:48.027 T:6221  NOTICE: CVideoPlayer::OnExit()`
`2020-05-07 15:38:48.155 T:5709  NOTICE: CVideoPlayer::CloseFile()`
`2020-05-07 15:38:48.164 T:5709  NOTICE: VideoPlayer: waiting for threads to exit`
`2020-05-07 15:38:48.165 T:5709  NOTICE: VideoPlayer: finished waiting`

**Comment by cdric61** [comment] 2020-05-07 13:41
And if I do it a second time, it works.

**Comment by cdric61** [comment] 2020-05-07 13:44
@Jalle19 I don't understand why it's a Kodi issue and not pvr.hts issue ?

**Comment by ksooo** [comment] 2021-01-10 22:03
Is this still an issue with latest Kodi v19 nightly builds and latest tvh4.3 builds? If I get no response within two weeks, I will close this issue.

**Comment by sakos** [comment] 2021-01-12 08:30
As the submitter of this issue, I do not object to close it. Nevertheless, I cannot confirm if it has been fixed or not as my setup has changed and this use case is not tested by me for long time.

**Closed** 2021-01-12 11:11 UTC
Labels: Kodi issue
