### ISSUE TITLE
Can't play any recordings (git latest)

### ISSUE THREAD

**Issue by PhobosK** [kodi-pvr/pvr.hts#139] opened 2015-11-28 15:26 UTC
This issue exists in both Gentoo and Ubuntu using latest code (git latest) of both pvr.hts and Kodi.
Any recording cannot be played at all. No info or warning issued in the UI.

**How to reproduce:**
Click on any recording (old or recorded with the current version of Kodi/pvr.hts). 
The encoding of the title of the recording is irrelevant (in the posted below log it is utf-8).

**What is expected:**
The recording to be played. It used to work a couple of months ago...

**What happens:**
Clicking on any recording does nothing - no UI warning, no start of playing the recording etc.

**Here is the log entry in Kodi:**

```
15:42:27 T:140337408288896  NOTICE: DVDPlayer: Opening: pvr://recordings/active/ДЕНЯТ, В КОЙТО ЗЕМЯТА СПРЯ, TV (Moviestar), 20150405_164500.pvr
15:42:27 T:140337408288896 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
15:42:27 T:140337408288896   DEBUG: CRenderManager::UpdateDisplayLatency - Latency set to 0 msec
15:42:27 T:140337408288896   DEBUG: LinuxRendererGL: Cleaning up GL resources
15:42:28 T:140337408288896   DEBUG: CLinuxRendererGL::PreInit - precision of luminance 16 is 16
15:42:28 T:140333905880832   DEBUG: Thread DVDPlayer start, auto delete: false
15:42:28 T:140333905880832  NOTICE: Creating InputStream
15:42:28 T:140333905880832   DEBUG: AddOnLog: Tvheadend HTSP Client: pvr.hts - vfs open file=dvr/791792914
15:42:28 T:140333905880832   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command fileOpen failed: DVR entry does not have a file yet
15:42:28 T:140333905880832   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - vfs failed to open file
15:42:28 T:140333905880832   ERROR: CDVDPlayer::OpenInputStream - error opening [pvr://recordings/active/ДЕНЯТ, В КОЙТО ЗЕМЯТА СПРЯ, TV (Moviestar), 20150405_164500.pvr]
15:42:28 T:140333905880832  NOTICE: CDVDPlayer::OnExit()
15:42:28 T:140333905880832   DEBUG: CDVDInputStreamPVRManager::Close - stream closed
15:42:28 T:140333905880832   DEBUG: OnPlayBackStopped: play state was 1, starting 1
15:42:28 T:140333905880832   DEBUG: Thread DVDPlayer 140333905880832 terminating

```

Here is the recording config entry at HTS server side from *~/.hts/tvheadend/dvr/log/12cd312ffcd041b19b4c3f54ed4ba9cf*

```
{
	"start": 1428252300,
	"start_extra": 0,
	"stop": 1428259500,
	"stop_extra": 0,
	"channel": "2c080c5e70a74d5dfd5cb6f514670088",
	"channelname": "Moviestar",
	"title": {
		"bul": "ДЕНЯТ, В КОЙТО ЗЕМЯТА СПРЯ"
	},
	"subtitle": {
		"bul": "ДЕНЯТ, В КОЙТО ЗЕМЯТА СПРЯ"
	},
	"description": {
		"bul": "-----SNIPPED------"
	},
	"pri": 2,
	"retention": 365,
	"container": -1,
	"config_name": "392f291eba53caaf035b38e150edd455",
	"owner": "-----SNIPPED------",
	"creator": "-----SNIPPED------",
	"errorcode": 0,
	"errors": 0,
	"data_errors": 14,
	"dvb_eid": 10729,
	"noresched": false,
	"autorec": "",
	"timerec": "",
	"content_type": 0,
	"broadcast": 67864544,
	"files": [
		{
			"filename": "/home/hts/Recordings/ДЕНЯТ, В КОЙТО ЗЕМЯТА СПРЯ.mkv"
		}
	]
}

```

No messages in the debug log of the HTS server considering any request for the file recording are found...

At the same time other frontends like TVGuide (android) etc work ok with the same recording...

Thanks

**Comment by ksooo** [comment] 2015-11-28 16:30
Which tvheadend version?

**Comment by Glenn-1990** [comment] 2015-11-28 19:18
> 15:42:28 T:140333905880832   ERROR: AddOnLog: Tvheadend HTSP Client: pvr.hts - Command fileOpen failed: DVR entry does not have a file yet

"DVR entry does not have a file yet" is an error from the server, we don't get the recording from tvheadend so we can't do anything about this in the pvr addon...
You should report it here: https://tvheadend.org/projects/tvheadend/issues

The other clients are probably working because they use another type of connection (kodi uses htsp)

**Comment by PhobosK** [comment] 2015-11-28 20:35
It's a HTS Tvheadend 4.1.18~gec3ba93.

Since TVHGuide (android) works I decided it is a pvr problem... Because the entry _dvr/791792914_ is prepared by pvr.hts...

Anyway I cannot get any debug trace of this on the server side (using all --trace --debug --stderr switches) though I see the info exchanged between Kodi and HTS server via wireshark.

What exactly to report on tvheadend issues then? Shouldn't this be a co-effort between the teams?

**Comment by ksooo** [comment] 2015-11-28 21:42
Sorry, tvh 4.1 is unstable software and therefore currently not supported by pvr.hts. pvr.hts is tested against stable version of tvh which currently is 4.0.7. Please test against 4.0.7 and report back if the problem also occurs with this version.

**Comment by Jalle19** [comment] 2015-11-30 08:35
I suspect it has to do with the Cyrillic characters in the file name. Can you attempt to play a recording that doesn't contain any special characters?

**Comment by PhobosK** [comment] 2015-12-01 05:12
No it is not the Cyrillic chars... As I said it is encoding independent... I tried with a short latin (5 letters, no special chars) name recording too and it is still not working....

**Comment by ksooo** [comment] 2015-12-01 05:49
Aren't you a coder? How about debugging this yourself? ;-)

**Comment by ksooo** [comment] 2015-12-06 16:27
@PhobosK honestly, I think this a regression with tvh 4.1. Please test against 4.0.7 and report back if the problem also occurs with this version.

**Comment by Jalle19** [comment] 2015-12-19 05:48
@PhobosK any update on this? Did you test with the `release/4.0` branch of tvheadend?

**Comment by PhobosK** [comment] 2015-12-19 11:14
@Jalle19 ,
Sorry I didn't have the time to test with stable releases (besides stable is not "my thing" when it comes to apps and using git versions ;) )....
Anyway now with the new git version of the TVHeadend - tvheadend_4.1-1235~gd822a74 and latest git of kodi, kodi-pvr -  recordings work as expected, so this bug is not valid anymore i guess...

Though there is another problem that I would have reported as a new bug, but since my experience here shows you work mainly on stable things... I decided not to...


Anyway here it is - you decide what to do ;)

libplatform changed their namespace from POLATFORM to P8PLATFORM ( Pulse-Eight/platform@cce6a497d63c436d770e5099f338e2bfb7aa369f ), so now kodi-pvr doesn't compile and needs update on that...

Thanks

**Comment by ksooo** [comment] 2015-12-19 11:25
Please do not hijack one issue to report a completely unrelated problem. If you want to officially report a problem, please open a separate issue for it. Thanks.

**Comment by PhobosK** [comment] 2015-12-19 11:38
LOL...
Sorry my fault... I was too much in a hurry...

Here we go: #149

**Comment by Jalle19** [comment] 2016-01-05 12:26
Closing this since @PhobosK couldn't reproduce anymore.

**Closed by Jalle19** 2016-01-05 12:26 UTC
Labels: Needs more info
