### ISSUE TITLE
Timeshift: buffering / stuttering after seeking in timeshift buffer

### ISSUE THREAD

**Issue by dkonerma** [kodi-pvr/pvr.hts#319] opened 2017-07-16 17:18 UTC
Hello,,

I'm using Kodi with TVH for many years now... and observed that timeshifting was never stable for me. Currently I'm using the latest Milhouse LibreELEC Leia build (#0715) with almost latest TVH. Bleeding edge though.

Timeshifting is failing completely for me on German channels like ZDF HD and ARD HD: These are 720p, whereas most other HD channels are 1080i and timeshift a lot better, not perfect also.

Example:
When I skip back into the timeshift buffer while watching ZDF HD 720p Live, then - after some seconds timeshifted playback - Kodi starts buffering ("busy circle") for several seconds. Afterwards playback resumes, but heavily stutters every few seconds. I also heave artifacts then, unwatchable. Skipping forward into LiveTV mode fixes the issue immediately.

When I do the very same with e.g. SAT1.HD 1080i, then I also see the buffering, which is annoying. But afterwards all is fine and watchable most of the time.

Here is a log of Kodi while doing the above steps.
http://sprunge.us/QIKE

Issues like these tend to bounce around between Kodi, PVR addon and TVH. Unfortunately Kodi Video folks (VDR promoters) don't really like to help wih TVH issues, IMHO. ;-)

Hope I can start the process to look into these issue here, in the "DMZ" between Kodi and TVH? ;-) Because Kodi with TVH is such a lovely solution... and stable timeshifting is the little remaining open issue before it gets nearly perfect.

Thanks
Dietmar.

**Comment by CvH** [comment] 2017-07-16 18:43
Just want to add that the same happens at windows too and overall it is not really stable to seek at timeshifted playback. Like said this is nothing new, never worked for me regardless of Tvh version. Everything beside pause/play is not use able. 

There were timeshift related fixes at Tvh in the past that made it much better, I am not too sure if the current situation isn't maybe due an Tvh server related bug.

**Comment by alexhass** [comment] 2017-12-05 21:54
Not only if you try to rewind...

Make a recording and than start viewing from start after 5 minutes. Use kabel1 or any other non-hd channel. When advertising start... wind over the advertising... when you reach the end of the recording the picture end with artefacts and sound issues. It never recovers. From logs i see ffmpeg causes out of order packets. The only workaround is stopping play and restarting. This is 100% reproducible.

I have never seen this with openelec v6 or v7. This started with libreelec v8 from my point of view.

**Comment by Hotk3y** [comment] 2018-02-17 16:44
I also have the exact same Problem. Is there any news or possible workaround?

**Comment by nkichukov** [comment] 2018-12-21 15:14
Hello,
The same is also observed when seeking in an active recording(not the timeshift function, though same concept) while it is still running. Forward seeking with fixed 30 seconds generates faster updates, within 4-6 seconds range, while random seek forward, say 10 minutes forward can take from 60 up to 120 seconds, it varies. If the recording has finished, but playback was started while it was recording, then seeking behaves as described above, even though it no longer records. But if you stop the playback and resume from current position on the fully recorded stream, then seeking becomes instant.

The storage is a CIFS network mount. See attachment dvr and profile configurations for tvheadend settings in use for the recordings. Matroska profile without webm.

This is reproduced on latest builds of kodi, kodi-pvr-hts and tvheadend stable on 32bit GNU/Gentoo running on raspberry pi 3B:

Linux ARM 32-bit version 4.19.6-v7+
pvr.hts v4.4.5 installed
Kodi (18.0-RC4 Git:20181216-922b68cae5-dirty)
tvheadend-4.2.7

[pvr-hts-tvheadend.settings.txt](https://github.com/kodi-pvr/pvr.hts/files/2703237/pvr-hts-tvheadend.settings.txt)

Thank you,
-N

**Comment by davincino** [comment] 2019-02-17 15:54
Last days I've upgraded Kodi from v17 to v18. Kodi and tvheadend are installed on same Lubuntu 18.04.2 system. I was using stable releases, but after getting issues I've changed to unstable release. This issue is still there. 
Live TV works fine. But when I skip back the video resumes immediately and after some seconds it's buffering round about 5 seconds, afterthat it resumes playback without issues. Kodi 18 is causing this issue. With v17 everything worked fine. 

Software:
Tvheadend = v4.2.8
Kodi = unstable Repo 18.1 (same issue with 18.0)

Hardware:
Core i7 8700t, 8GB RAM, SSD

Together with kodi v18, also this addon was upgraded.

**Comment by jahutchi** [comment] 2019-02-20 12:16
@davincino I have the exact same problems with time shifting in kodi v18 (was fine in krypton).

It's also reported here: https://forum.kodi.tv/showthread.php?tid=325178

**Comment by dkonerma** [comment] 2019-02-20 14:07
I'm hoping that this commit in master will improve things. No yet tested
myself.
https://github.com/kodi-pvr/pvr.hts/commit/f6d248a766fe1b6af318d7e66448e23f9bdb9565#r32349769

Cheers
Dietmar.

Am Mi., 20. Feb. 2019 um 13:16 Uhr schrieb jahutchi <
notifications@github.com>:

**Comment by jahutchi** [comment] 2019-02-20 14:15
FTR: I am using pvr.hts v4.4.13 against leia 18.1.

**Comment by ksooo** [comment] 2019-02-20 15:18
Latest is 4.4.14, which contains the (potential) fix.

**Comment by ksooo** [comment] 2019-02-20 15:22
Technically, two different problems:

> When I skip back into the timeshift buffer while watching ZDF HD 720p Live, then - after some seconds timeshifted playback - Kodi starts buffering ("busy circle") for several seconds. 

 Should be fixed in 4.4.14

> Afterwards playback resumes, but heavily stutters every few seconds. I also heave artifacts then, unwatchable. Skipping forward into LiveTV mode fixes the issue immediately.

 No fix available yet. As far as I know this only happend with 720p channels (like German ZDF HD). There are rumors that this is caused by a tvheadend bug (I-frames handling when timeshifting or the like), but it's only rumors...

**Comment by davincino** [comment] 2019-02-20 15:43
Is v4.4.14 included in nightly repo or should I compile this version by myself?

**Comment by alexhass** [comment] 2019-02-20 17:46
Tvheadend with timeshift enabled is extremly unstable. It crashes with both in memory and to disk mode. I was forced to disable it completly as all at home have seen crashing tvheadend and kodi every few hours. Cvh has confirmed this is known, but not that massive. He told me he has no issues with in memory only, but I cannot confirm this. This issues exists for about ~6months in libreelec. Aside this is not only ZDF, this ia also on every other private like pro7/rtl/vox and so on. An htpc without timeshift is really a useless device.

**Comment by davincino** [comment] 2019-02-20 19:42
I've installed latest version 4.4.14
Now timeshift is working like a charm. Thank you for the fix. Channels at 720p resume also immediately after skip within timeshift, but after some seconds there can be freezer.
It's a known issue from the past and not related to kodi v18 (combined with new pvr.hts).

**Comment by ksooo** [comment] 2019-02-20 22:34
@alexhass whatever your massive problems with timeshift are, those have other root cause than the problems discussed in this issue. This is about single buffering and continuous micro stuttering with 720p channels after pausing/rewinding.

It makes no sense to use this issue to report all kind of timeshift problems. Please refrain from this and open a separate issue where you describe in detail what your problems are and where you attach a debug log file with pvr.hts trace enabled and service.log form tvheadend. Thanks.

@davincino thanks for reporting back.

**Comment by jahutchi** [comment] 2019-02-21 07:59
I've also upgraded to v 4.4.14 and timeshift is working perfectly for me now too. Thanks @ksooo for this, and all the great work you do.

**Comment by alexhass** [comment] 2019-02-21 08:05
@ksooo: yes, it is tvheadend that is crashing. Collecting logs is impossible as tvheadend crashes and than auto restart. When it auto restarts the logfile with crash information is overwritten and therefore lost. No chance to identify the crash. There is no logfile rollover or keep the last logfile in libreelec...

**Comment by ksooo** [comment] 2019-02-21 08:28
If tvheadend is crashing, then this issue is the wrong place to report this. You should instead open a ticket for tvheadend at tvheadend.org.

**Comment by ksooo** [comment] 2019-02-21 08:30
@jahutschi thanks for reporting back and for the nice wird. You're welcome. 😀

**Comment by Jalle19** [comment] 2019-02-26 08:49
Should we consider this closed if things work better in 4.4.14?

**Comment by davincino** [comment] 2019-02-26 08:58
I'm using 4.4.14 and after skip back the system is not buffering anymore. But sometimes (not reproducible) live tv is stuttering after some minutes.
I don't know if the fix is causing  this issue. With old stable version, 4.4.12, I've got buffering for some seconds but afterthat live tv worked really fine.

**Comment by dkonerma** [comment] 2019-02-26 10:39
Like @ksooo wrote, I actually reported two issues here and the really annoying one still stands, unfortunately: the stuttering in Timeshift with 720p channels (after some minutes watching). I'm still testing with the new 4.4.14,  tvheadend master.
Would be interesting to get tvh guro @perexg into the discussion... and maybe also videoplayer and streaming guru @FernetMenta. This issue was meant to get the different parties work todether... I'm happy to assisist in testing and delivering traces at any time.

Keeping the fingers crossed to get this finally sorted our. Last major bug in this solution IMHO.

**Comment by FernetMenta** [comment] 2019-02-26 11:08
see my comments here: https://github.com/kodi-pvr/pvr.hts/pull/403

this change is actually not a proper fix because it does not allow the demux buffer to be filled in timeshift mode.

**Comment by ksooo** [comment] 2019-02-26 12:36
@FernetMenta imo we are talking about two issues with different rot cause each. 

The buffering after skip back is the one "fixed" with  4.4.14, people confirm the fix working. 

The continuous stuttering with only 720p channels after pausing/unpausing live tv is unrelated to the 4.4.14 change. There are people out there claiming they have debugged tvheadend and found that the issue is there. Don't know any more  details about that story, sorry.

**Comment by dkonerma** [comment] 2019-02-26 13:17
btw, also reported to tvh, https://tvheadend.org/issues/4831

**Comment by ksooo** [comment] 2019-02-26 13:24
Nobody at the tvheadend side  seems to care... :-/

**Comment by dkonerma** [comment] 2019-02-26 13:48
Well, Kai. ;-)
720p issues are not that relevant outside Germany, I'm afraid. And @perexg is the only real tvh dev, being quite busy. That's how it is, unfortunately.
To you my warmest compliments and thanks for your hard work on the Kodi PVR side of things. Very much appreciated... 
We are using it daily as our main live TV setup on a dirt cheap China Amlogic box. Works like a charm, with this last real issue open.

Cheers 
Dietmar.

**Comment by malvinas2** [comment] 2019-02-26 13:59
Dietmar, you're right that 720p is not that relevant outside Germany, because other countries -as well as private stations in Germany- are using 1080i50. But does this issue not occur in higher resolutions, e.g. the mentioned 1080? I always assumed it is related to higher data rates?

**Comment by dkonerma** [comment] 2019-02-26 14:02
Nope, 1080i streams are working fine without that issue, at least here with my setup.

**Comment by perexg** [comment] 2019-02-26 14:17
There is no 720p problem, but there are probably litttle problems with the specific encoder settings. From my investigation, German 720p channels does really heavy frame reordering (up to one or two seconds) to save the bandwidth and it seems that the player code is confused (DTS/PTS). Unfortunately, we are doing a bit ping-pong here, because everytime when I ask for the timing details where things are breaking about the player the answer is - other PVR backends are fine, so find the bug yourself. And no, I don't use kodi in my environment (sorry).

**Comment by dkonerma** [comment] 2019-02-26 14:30
> Unfortunately, we are doing a bit ping-pong here

Hey, actually this was the reason for me to start this thread in 2017, here in the "DMZ" between Kodi and TVH. ;-) At least folks seems to be talking now, which may be good news.

@perexg:  in general Kodi's is playing these channels quite fine... what is special when playing time-shifted? Isn't the same "heavy frame reordering" in place?

**Comment by FernetMenta** [comment] 2019-02-26 14:55
I logged out dts coming from tvh when doing timeshift. Very obvious that tvh messes up the data.

**Comment by perexg** [comment] 2019-02-26 15:01
I need more info. The packet order for the elementary streams should be kept.

**Comment by FernetMenta** [comment] 2019-02-26 15:03
dts should be in order and increasing in steps of 20ms. the do fine when stream is started. after doing some jumping in timeshift buffer I get this:

```
2019-02-26 15:58:54.768 T:123145513512960  NOTICE: ----------- dts: 14978.244000
2019-02-26 15:58:54.787 T:123145513512960  NOTICE: ----------- dts: 15058.244000
2019-02-26 15:58:54.806 T:123145513512960  NOTICE: ----------- dts: 15138.244000
2019-02-26 15:58:54.827 T:123145513512960  NOTICE: ----------- dts: 15218.244000
2019-02-26 15:58:54.846 T:123145513512960  NOTICE: ----------- dts: 15298.244000
2019-02-26 15:58:54.868 T:123145513512960  NOTICE: ----------- dts: 15318.244000
2019-02-26 15:58:54.869 T:123145513512960   DEBUG: CPtsTracker: detected pattern of length 1: 20000.00, frameduration: 20000.000000
2019-02-26 15:58:54.887 T:123145513512960  NOTICE: ----------- dts: 15398.244000
2019-02-26 15:58:54.907 T:123145513512960  NOTICE: ----------- dts: 15478.244000
2019-02-26 15:58:54.928 T:123145513512960  NOTICE: ----------- dts: 15558.244000
2019-02-26 15:58:54.949 T:123145513512960  NOTICE: ----------- dts: 15638.244000
2019-02-26 15:58:54.968 T:123145513512960  NOTICE: ----------- dts: 15718.244000
2019-02-26 15:58:54.987 T:123145513512960  NOTICE: ----------- dts: 15798.244000
2019-02-26 15:58:55.007 T:123145513512960  NOTICE: ----------- dts: 15878.244000
2019-02-26 15:58:55.007 T:123145513512960   DEBUG: CPtsTracker: pattern lost on diff 80000.000000, number of losses 3
2019-02-26 15:58:55.028 T:123145513512960  NOTICE: ----------- dts: 15958.244000
2019-02-26 15:58:55.050 T:123145513512960  NOTICE: ----------- dts: 16038.244000
2019-02-26 15:58:55.069 T:123145513512960  NOTICE: ----------- dts: 16118.244000
2019-02-26 15:58:55.088 T:123145513512960  NOTICE: ----------- dts: 16138.244000
2019-02-26 15:58:55.108 T:123145513512960  NOTICE: ----------- dts: 16218.244000
2019-02-26 15:58:55.187 T:123145513512960  NOTICE: ----------- dts: 16298.244000
2019-02-26 15:58:55.265 T:4436366784   DEBUG: ------ Window Deinit (DialogSeekBar.xml) ------
2019-02-26 15:58:55.265 T:4436366784   DEBUG: ------ Window Deinit (Custom_1109_TopBarOverlay.xml) ------
2019-02-26 15:58:55.268 T:123145513512960  NOTICE: ----------- dts: 16378.244000
2019-02-26 15:58:55.346 T:123145513512960  NOTICE: ----------- dts: 16458.244000
2019-02-26 15:58:55.425 T:123145513512960  NOTICE: ----------- dts: 16538.244000
2019-02-26 15:58:55.505 T:123145513512960  NOTICE: ----------- dts: 16618.244000
2019-02-26 15:58:55.525 T:123145513512960  NOTICE: ----------- dts: 16698.244000
2019-02-26 15:58:55.526 T:123145513512960  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: lost diff
```

**Comment by perexg** [comment] 2019-02-26 15:13
Could you give me also '--trace timeshift' with this type of kodi log from tvh to analyze what's wrong? The DTS time from this kodi log is in seconds (same as pvr.hts received - unaltered), right?

**Comment by FernetMenta** [comment] 2019-02-26 15:22
dts/pts are converted by 
#define TVH_TO_DVD_TIME(x) (static_cast<double>(x) * DVD_TIME_BASE / 1000000.0f)

Kodi uses micros. I logged millis for better reading

**Comment by FernetMenta** [comment] 2019-02-26 15:30
trace: http://paste.ubuntu.com/p/9t2qfWn8fT/

```
2019-02-26 16:25:41.051 T:123145495584768  NOTICE: ----------- dts: 18946.244000
2019-02-26 16:25:41.071 T:123145495584768  NOTICE: ----------- dts: 19026.244000
2019-02-26 16:25:41.151 T:123145495584768  NOTICE: ----------- dts: 19106.244000
2019-02-26 16:25:41.231 T:123145495584768  NOTICE: ----------- dts: 19186.244000
2019-02-26 16:25:41.311 T:123145495584768  NOTICE: ----------- dts: 19266.244000
2019-02-26 16:25:41.391 T:123145495584768  NOTICE: ----------- dts: 19346.244000
2019-02-26 16:25:41.470 T:123145495584768  NOTICE: ----------- dts: 19426.244000
2019-02-26 16:25:41.491 T:123145495584768  NOTICE: ----------- dts: 19446.244000
2019-02-26 16:25:41.491 T:123145495584768  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: lost diff
2019-02-26 16:25:41.570 T:123145495584768  NOTICE: ----------- dts: 19526.244000
2019-02-26 16:25:41.650 T:123145495584768  NOTICE: ----------- dts: 19606.244000
2019-02-26 16:25:41.730 T:123145495584768  NOTICE: ----------- dts: 19686.244000
2019-02-26 16:25:41.810 T:123145495584768  NOTICE: ----------- dts: 19766.244000
2019-02-26 16:25:41.891 T:123145495584768  NOTICE: ----------- dts: 19846.244000
2019-02-26 16:25:41.971 T:123145495584768  NOTICE: ----------- dts: 19926.244000
2019-02-26 16:25:42.051 T:123145495584768  NOTICE: ----------- dts: 20006.244000
2019-02-26 16:25:42.130 T:123145495584768  NOTICE: ----------- dts: 20086.244000
2019-02-26 16:25:42.150 T:123145495584768  NOTICE: ----------- dts: 20126.244000
2019-02-26 16:25:42.230 T:123145495584768  NOTICE: ----------- dts: 20146.244000
2019-02-26 16:25:42.311 T:123145495584768  NOTICE: ----------- dts: 20166.244000
2019-02-26 16:25:42.311 T:123145495584768  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 74545
2019-02-26 16:25:42.311 T:123145498267648   ERROR: ffmpeg[70000BAE1000]: [h264] co located POCs unavailable
2019-02-26 16:25:42.390 T:123145495584768  NOTICE: ----------- dts: 20186.244000
2019-02-26 16:25:42.470 T:123145495584768  NOTICE: ----------- dts: 20206.244000
2019-02-26 16:25:42.550 T:123145495584768  NOTICE: ----------- dts: 20226.244000
2019-02-26 16:25:42.630 T:123145495584768  NOTICE: ----------- dts: 20246.244000
2019-02-26 16:25:42.710 T:123145495584768  NOTICE: ----------- dts: 20266.244000
2019-02-26 16:25:42.790 T:123145495584768  NOTICE: ----------- dts: 20286.244000
2019-02-26 16:25:42.811 T:123145495584768  NOTICE: ----------- dts: 20306.244000
2019-02-26 16:25:42.890 T:123145495584768  NOTICE: ----------- dts: 20326.244000
2019-02-26 16:25:42.971 T:123145495584768  NOTICE: ----------- dts: 20346.244000
2019-02-26 16:25:43.051 T:123145495584768  NOTICE: ----------- dts: 20366.244000
2019-02-26 16:25:43.131 T:123145495584768  NOTICE: ----------- dts: 20386.244000
2019-02-26 16:25:43.210 T:123145495584768  NOTICE: ----------- dts: 20406.244000
2019-02-26 16:25:43.290 T:123145495584768  NOTICE: ----------- dts: 20426.244000
2019-02-26 16:25:43.370 T:123145495584768  NOTICE: ----------- dts: 20446.244000
2019-02-26 16:25:43.451 T:123145495584768  NOTICE: ----------- dts: 20466.244000
2019-02-26 16:25:43.451 T:123145495584768  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: lost diff
```

**Comment by perexg** [comment] 2019-02-26 15:39
I am afraid, the traces can be stored to a file only: https://tvheadend.org/projects/tvheadend/wiki/Traces

**Comment by FernetMenta** [comment] 2019-02-26 15:49
```
2019-02-26 16:39:43.401 T:123145524416512  NOTICE: ----------- dts: 53738.244000
2019-02-26 16:39:43.418 T:123145524416512  NOTICE: ----------- dts: 53818.244000
2019-02-26 16:39:43.439 T:123145524416512  NOTICE: ----------- dts: 53898.244000
2019-02-26 16:39:43.458 T:123145524416512  NOTICE: ----------- dts: 53978.244000
2019-02-26 16:39:43.477 T:123145524416512  NOTICE: ----------- dts: 54058.244000
2019-02-26 16:39:43.500 T:123145524416512  NOTICE: ----------- dts: 54138.244000
2019-02-26 16:39:43.518 T:123145524416512  NOTICE: ----------- dts: 54218.244000
2019-02-26 16:39:43.538 T:123145524416512  NOTICE: ----------- dts: 54298.244000
2019-02-26 16:39:43.558 T:123145524416512  NOTICE: ----------- dts: 54378.244000
2019-02-26 16:39:43.578 T:123145524416512  NOTICE: ----------- dts: 54458.244000
2019-02-26 16:39:43.600 T:123145524416512  NOTICE: ----------- dts: 54538.244000
2019-02-26 16:39:43.618 T:123145524416512  NOTICE: ----------- dts: 54618.244000
2019-02-26 16:39:43.638 T:123145524416512  NOTICE: ----------- dts: 54698.244000
2019-02-26 16:39:43.658 T:123145524416512  NOTICE: ----------- dts: 54778.244000
2019-02-26 16:39:43.677 T:123145524416512  NOTICE: ----------- dts: 54798.244000
2019-02-26 16:39:43.700 T:123145524416512  NOTICE: ----------- dts: 54878.244000
2019-02-26 16:39:43.718 T:123145524416512  NOTICE: ----------- dts: 54958.244000
2019-02-26 16:39:43.718 T:123145524416512  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: lost diff
```

[trace.log](https://github.com/kodi-pvr/pvr.hts/files/2906281/trace.log)

**Comment by perexg** [comment] 2019-02-26 19:57
From you explanation, 53738.244000 = 53.738244 seconds, right? The frames for elementary stream 1 (video) are written here to the next layers (htsp server):

<pre>
2019-02-26 16:39:28.107 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type P pts   53838266 dts   53738244 dur       1800 len  68719 time       55018266
2019-02-26 16:39:28.108 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   53798266 dts   53758244 dur       1800 len  43327 time       55018266
2019-02-26 16:39:28.108 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   53778266 dts   53778244 dur       1800 len   2048 time       55018266
2019-02-26 16:39:28.108 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   53818266 dts   53798244 dur       1800 len    512 time       55018266
2019-02-26 16:39:28.108 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type P pts   53918266 dts   53818244 dur       1800 len  68338 time       55018266
2019-02-26 16:39:28.108 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   53878266 dts   53838244 dur       1800 len  42986 time       55018266
2019-02-26 16:39:28.108 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   53858266 dts   53858244 dur       1800 len   2053 time       55018266
2019-02-26 16:39:28.108 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   53898266 dts   53878244 dur       1800 len    523 time       55018266
2019-02-26 16:39:28.108 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type I pts   53998266 dts   53898244 dur       1800 len 124548 time       55018266
2019-02-26 16:39:28.109 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   53958266 dts   53918244 dur       1800 len  50528 time       55018266
2019-02-26 16:39:28.109 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   53938266 dts   53938244 dur       1800 len   2496 time       55018266
2019-02-26 16:39:28.109 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   53978266 dts   53958244 dur       1800 len     83 time       55018266
2019-02-26 16:39:28.109 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type P pts   54078266 dts   53978244 dur       1800 len  84028 time       55018266
2019-02-26 16:39:28.109 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   54038266 dts   53998244 dur       1800 len  44386 time       55018266
2019-02-26 16:39:28.109 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   54018266 dts   54018244 dur       1800 len   2302 time       55018266
2019-02-26 16:39:28.109 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   54058266 dts   54038244 dur       1800 len     98 time       55018266
2019-02-26 16:39:28.109 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type P pts   54158266 dts   54058244 dur       1800 len  65425 time       55018266
2019-02-26 16:39:28.109 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   54118266 dts   54078244 dur       1800 len  41938 time       55018266
2019-02-26 16:39:28.109 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   54098266 dts   54098244 dur       1800 len   2050 time       55018266
2019-02-26 16:39:28.109 [  TRACE]:timeshift: ts 12 pkt out - stream 1 type B pts   54138266 dts   54118244 dur       1800 len    552 time       55018266
</pre>

So it seems that B-frames are somewhere dropped.

The HTSP protocol has another feature which drops the frames/packets when a threshold is reached and it starts with the B-frames. Could you retest with this patch?

<pre>
diff --git a/src/htsp_server.c b/src/htsp_server.c
index a7f8a79e0..f1ed9ba1d 100644
--- a/src/htsp_server.c
+++ b/src/htsp_server.c
@@ -4017,7 +4017,7 @@ htsp_stream_deliver(htsp_subscription_t *hs, th_pkt_t *pkt)
     return;
   }
 
-  if(video &&
+  if(0 && video &&
      ((qlen > hs->hs_queue_depth     && pkt->v.pkt_frametype == PKT_B_FRAME) ||
       (qlen > hs->hs_queue_depth * 2 && pkt->v.pkt_frametype == PKT_P_FRAME) ||
       (qlen > hs->hs_queue_depth * 3))) {
</pre>

Or pvr.hts can set the "queueDepth" parameter in the subscription method. The default value is  500000 which seems to be a bit small for fast forward (speed 400% or more).

**Comment by ksooo** [comment] 2019-02-26 21:23
Thanks @perexg. What would be a good value for "queueDepth"?

**Comment by ksooo** [comment] 2019-02-26 21:34
pvr.hts already sets "queueDepth" to 2000000. 

https://github.com/kodi-pvr/pvr.hts/blob/master/src/tvheadend/Subscription.cpp#L138
https://github.com/kodi-pvr/pvr.hts/blob/master/src/tvheadend/Subscription.h#L63

Is this still to small? Again, what would be a good value?

**Comment by Trujulu** [comment] 2019-02-26 22:27
> Thanks @perexg. What would be a good value for "queueDepth"?

What about patch? Does it work?

**Comment by ksooo** [comment] 2019-02-26 22:30
> What about tvh patch? Does it work?

 Sorry, bed time here. If you find some time for testing I would be glad to hear from you.

**Comment by FernetMenta** [comment] 2019-02-27 06:54
> From your explanation, 53738.244000 = 53.738244 seconds, right?

Right. Away from my systems during the day. Can do further tests in the evening. Note that I already run modified versions of Kodi and pvr.hts that have corrects some weaknesses.

**Comment by ksooo** [comment] 2019-02-27 07:00
> Note that I already run modified versions of Kodi and pvr.hts that have corrects some weaknesses.

 Would be great if you could  PR those fixes, so that all users can benefit. Thanks.

**Comment by dkonerma** [comment] 2019-02-27 08:01
With a tear in the eye I really feel that the problem is finally fixed. Snief. ;-)

Actually this issue was quite easy to duplicate with my setup. After applying the patch on my tvh server I'm unable to do so... and I tried a lot this morning.

So, folks. Looks like you finally did it. At least I hope so, I'm quite confident.

**Comment by perexg** [comment] 2019-02-27 09:02
Looking again to the collected logs, I think that we are missing the "big picture" for the data streaming when the timeshift is activated. The full queue is just a symptom that the server/client sync is broken.

If we look to the tvh logs from comment , this type of operations are done:

| Time | Operation | Speed | Video DTS | Expected DTS
| ------ | ------------- | -------- | ------- | -----
| 16:38:15 | live play | |
| | | |
| 16:38:41 | rewind to start | 100% | 1.778-2.818 | ok
| 16:38:41 | fast forward | 400% | 2.838-16.298 | 
| 16:38:48 | play | 100% | 16.338-27.518
| | | |
| 16:39:00 | rewind to start | 100% | 0.958-1.938
| 16:39:00 | fast forward | 400% | 1.958-12.598
| 16:39:01 | play | 100% | 12.618-12.698
| 16:39:01 | fast forward | 400% | 12.718-16.298
| 16:39:01 | play | 100% | 16.318-14.578
| 16:39:04 | fast forward | 400% | 14.598-21.858
| 16:39:05 | play | 100% | 21.878-25.458
| 16:39:09 | fast forward | 400% | 25.478-27.518
| 16:39:09 | play | 100% | 27.538-36.538
| 16:39:17 | seek to 16.501 | 100% | 16.238-16.298
| 16:39:17 | fast forward | 400% | 16.338-24.398
| 16:39:18 | play | 100% | 24.418-25.458
| 16:39:19 | seek to 8.128 | 100% | 6.538-6.858
| 16:39:19 | fast forward | 400% | 6.878-16.298
| 16:39:22 | seek to 1.866 | 100% | 1.778-2.738
| 16:39:22 | fast forward | 400% | 2.758-12.698
| 16:39:23 | play | 100% | 12.718-16.238
| 16:39:26 | seek to 35.820 | 100% | 36.378-36.558
| 16:39:26 | fast forward | 400% | 36.578-47.658
| 16:39:28 | play | 100% | 47.678-48.638
| 16:39:28 | fast forward | 400% | 48.658-65.538
| 16:39:28 | play | 100% | 65.558-82.418
| 16:39:44 | end

It looks that the problem is that tvh sends a lot of data to the client when speed=400% (very visible at 16:39:26 and 16:39:28). I am looking further to logs to analyze the issue.

**Comment by perexg** [comment] 2019-02-27 09:03
> With a tear in the eye I really feel that the problem is finally fixed. Snief. ;-)
> 
> Actually this issue was quite easy to duplicate with my setup. After applying the patch on my tvh server I'm unable to do so... and I tried a lot this morning.
> 
> So, folks. Looks like you finally did it. At least I hope so, I'm quite confident.

Nope, the patch is just a workaround for the real issue. You may hit other wrong behaviour with it.

**Comment by dkonerma** [comment] 2019-02-27 09:52
Jaroslav, thank for looking into it.
Concerning "a lot of data to the client when speed=400%"... I'm quite sure that the issue could be duplicated without using seek at all. Just pausing some time and continue playing in timeshift is enough to trigger the stuttering.

**Comment by FernetMenta** [comment] 2019-02-27 10:45
@perexg Kodi sets speed to 400 in timeshift mode when it wants to fill its internal buffers. It could read even faster but AFAIK tvh would turn into keyframe mode then.

**Comment by perexg** [comment] 2019-02-27 11:40
> @perexg Kodi sets speed to 400 in timeshift mode when it wants to fill its internal buffers. It could read even faster but AFAIK tvh would turn into keyframe mode then.

Then it looks like a protocol "misuse", but it explains the behaviour. I found another 100%->400% change and added it to the table. Each speed change sets the new time threshold (the client time), so if the client does 100%-400%-100%-400% rapidly, tvh sends a lot of data (there is build-in one second ahead threshold, too). There's some delay between data delivery, but it seems that kodi issues the new speed change request before it waits for the new data, thus they are buffered in the tvh (and dropped due to the congestion filter).

Personally, I am not happy with the current timeshift protocol at all (I inherited it from the past and occasionally trying to fix it). It is somewhat difficult to compute the client expectations (how many frames should be sent ahead and especially track the actual client position - from logs, you can see the big desync - the server sends much more data ahead and other parts in tvh starts to protect the total network congestion).

We have several ways to resolve this. The easiest way is to remove the current protocol and use the polled one (which you somewhat simulate), like - I want elementary streams from DTS A to B (or PTS as you like). Done. No states, no double position tracking, easy to implement on the server side. This will move the data flow arbitration completely to the client as you probably expect.

**Comment by FernetMenta** [comment] 2019-02-27 12:02
> The easiest way is to remove the current protocol and use the polled one

sounds good imo

**Comment by ksooo** [comment] 2019-02-28 06:44
@perexg @FernetMenta the 720p stuttering also occurs on  changes 100->0->100, not only on changes 100->greater 100->100. So, no heavy data traffic needed to run into the problem, imo.

Does this fit into your problem analysis and the derived idea for solution?

**Comment by FernetMenta** [comment] 2019-02-28 10:37
I can do pvr.hts once tvh provides this new interface. @perexg do you have time to implement this in the near future?

**Comment by FernetMenta** [comment] 2019-02-28 10:59
@ksooo in the meantime you can fix https://github.com/kodi-pvr/pvr.hts/blob/bd64b9e1aef0bf3043643dbbff520a0ce6511e88/src/tvheadend/HTSPDemuxer.h#L119

pktBuffer silently eats packets received from tvh. By default it can buffer 100 packets which is not much considering that channels like ZDF have at least 2 audio streams + teletext + subtilte + video.

**Comment by ksooo** [comment] 2019-02-28 11:19
> I can do pvr.hts once tvh provides this new interface.

 Great.

> By default it can buffer 100 packets which is not much considering that channels like ZDF have at least 2 audio streams + teletext + subtilte + video

 What would be a good value?

**Comment by ksooo** [comment] 2019-02-28 11:28
> By default it can buffer 100 packets which is not much considering that channels like ZDF have at least 2 audio streams + teletext + subtilte + video

https://github.com/kodi-pvr/pvr.hts/blob/master/src/tvheadend/HTSPDemuxer.cpp#L47 => paket buffer should be large enough already

**Comment by FernetMenta** [comment] 2019-02-28 13:15
@ksooo sorry I missed this old school ctor init and a c-cast hack :)

@perexg I increased queueDepth to 10000000 and issues seem to be gone. Still my version that sets speed to 400

**Comment by perexg** [comment] 2019-02-28 13:22
@FernetMenta : Please, ensure also that you don't do the 100-400-100-400 transitions quickly (wait for the answer and probably use speed 0 (pause) if there are many packets in the client's queue - you can use the real time to do it). As I said, the increased buffer is just a workaround and it affects the memory usage on the server.

**Comment by moje1977** [comment] 2019-06-03 08:59
Been following this one since i'm experiencing very unrelyable timeshifting with my IPTV setup. Been trying to nail down if this really is the same, but as with @dkonerma i have alot of (swedish) streams in 720p.

I'm running TVHeadend 4.3-1792~g466a01431 (2019-05-20T17:02:26) and KODI client (leia) with latest official pvr.hts.

What i'm wondering is if this patch/fix is included in that build of TVH? Have tried to verify but guess my git-knowledge fails me here :o

**Comment by dkonerma** [comment] 2019-06-03 09:34
ksooo increased queueDepth to 10000000, see
https://github.com/kodi-pvr/pvr.hts/commit/1690ecf196fff8a27cada9c04aa31765956571c6
It's in pvr.hts from 4.4.16 onwards.

Cheers
Dietmar.

**Comment by moje1977** [comment] 2019-06-03 09:46
Thanks Dietmar!

I think i run 4.4.17. Cannot verify from work now. But that was the workaround part, right? Was there no fix in TVH by @perexg aswell?

**Comment by ksooo** [comment] 2019-06-03 10:33
No, no fix in TVH so far. Increased queue depth size in pvr.hts seems to solve the problem. At least I have not heard anything else so far.

**Comment by moje1977** [comment] 2019-06-03 11:00
Thanks @dkonerma  and @ksooo for quick replies. Still issues like described here in my setup. And timeshifting cannot be trusted....

**Comment by ksooo** [comment] 2021-01-10 22:01
Is this still an issue with latest Kodi v19 nightly builds and tvh 4.3+? If I get no response within two weeks, I will close this issue.

**Comment by dkonerma** [comment] 2021-01-14 07:36
Hi ksooo,

working fine here. Feel free to close and many thanks for your efforts!

Cheers.

Kai Sommerfeld <notifications@github.com> schrieb am So., 10. Jan. 2021,
23:01:

**Closed** 2021-01-14 08:53 UTC
