### ISSUE TITLE
Stutters when playing BBC channels

### ISSUE THREAD

**Issue by Leatherface75** [kodi-pvr/pvr.hts#233] opened 2016-07-08 02:45 UTC
I have problems with stutters with BBC streams from IPlayer added in TVheadend.
Same streams works as it should with BBC Iplayer WWW addon and VLC.
Same streams works if i add url in a .m3u file and opens it in Kodi.
But if i open same stream in pvr.hts addon it stutters.
Using current git versions.

Here is a few examples:
http://vs-hls-uk-live.edgesuite.net/pool_30/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d5070000.m3u8
http://vs-hls-uk-live.edgesuite.net/pool_1/live/bbc_parliament/bbc_parliament.isml/bbc_parliament-pa3%3d96000-video%3d1604000.norewind.m3u8
http://vs-hls-uk-live.edgesuite.net/pool_34/live/bbc_news_channel_hd/bbc_news_channel_hd.isml/bbc_news_channel_hd-pa4%3d128000-video%3d5070000.m3u8

**Comment by Leatherface75** [comment] 2016-07-25 23:04
I tried same streams with IPTV Simple Client and no problem with playback there.
So the problem is with pvr.hts client.

**Comment by ksooo** [comment] 2016-07-26 09:47
> So the problem is with pvr.hts client.

wrong. the problem is almost 100% with tvheadend.

**Comment by Jalle19** [comment] 2016-07-26 10:02
Does the same thing happen if you play the stream from tvheadend in VLC?

**Comment by Leatherface75** [comment] 2016-07-26 10:50
No it's not tvheadend?
It works in VLC.
It works if i add tvheadend url in m3u file and opens i Kodi.
It works if i add tvheadend url in Simple IPTV addon in Kodi.
But if i open in pvr.hts it stutters so yes it's a problem with pvr.hts.
Same thing happens with some other streams.

**Comment by Jalle19** [comment] 2016-07-27 13:03
Can you post a Kodi debug log where you play one of these streams?

**Comment by Leatherface75** [comment] 2016-07-27 22:39
http://pastebin.com/WPzUrH4e

**Comment by FernetMenta** [comment] 2016-07-28 06:00
truncated logs are worth nothing

**Comment by Leatherface75** [comment] 2016-07-28 06:02
That's the relevant part of the log when playing that stream.
But you maybe can tell me what's missing?

**Comment by FernetMenta** [comment] 2016-07-28 06:06
The entire log is missing. If you claim to know what is relevant and what is not, you should be able to track down and fix the issue yourself. If this is not the case only post complete logs.

**Comment by Leatherface75** [comment] 2016-07-28 06:13
Jalle19 told me to post where i play one of these streams and i did that.
It's not a problem with drivers or anything like that either because it works perfectly with everything else except pvr.hts so it's not a Kodi problem itself.
But as you wish i can try to fix another log later.

**Comment by Jalle19** [comment] 2016-07-28 06:18
I meant the complete log too, sorry for the confusion.

**Comment by Leatherface75** [comment] 2016-07-28 07:17
Here it is

https://ufile.io/d26c3

**Comment by Jalle19** [comment] 2016-07-28 13:24
Looked through the log briefly and I can't see any glaring issues. Have you tried turning off predictive tuning from the addon settings?

**Comment by Leatherface75** [comment] 2016-07-28 13:29
I tried that now and still same problem.
Same problem with dutch NPO channels for other examples so not only BBC channels.
And bandwidth shows about half the bitrate than it should.

**Comment by Jalle19** [comment] 2016-07-28 13:32
Can you try disabling trace debugging and predictive tuning in the addon and post a new debug log?

**Comment by Leatherface75** [comment] 2016-07-28 18:59
https://ufile.io/4d892

**Comment by Leatherface75** [comment] 2016-07-28 23:36
I see one difference now compared to VLC, Simple IPTV client etc.
pvr.hts uses htsp profile and the others pass profile.
Maybe htsp protocol does something with the stream that some stream doesn't like?

**Comment by Jalle19** [comment] 2016-07-29 09:14
@FernetMenta there's a lot of this in the logs:

```
DEBUG: ffmpeg[7FE5DA50E980]: [swscaler] Forcing full internal H chroma due to input having non subsampled chroma
```

and this:

```
DEBUG: ffmpeg[7FE50F648700]: [h264] nal_unit_type: 9, nal_ref_idc: 0
DEBUG: ffmpeg[7FE50F648700]: [h264] nal_unit_type: 1, nal_ref_idc: 1
DEBUG: Previous line repeats 3 times.
```

@perexg I'm assuming that tvheadend doesn't properly parse these streams? AFAIK the streams in this case are HLS.

**Comment by Jalle19** [comment] 2016-07-29 09:20
@Leatherface75 I hate to break it to you but apparently a bug has snuck into Kodi which has caused your tvheadend password to appear in your debug log. I suggest you remove the logs and/or change your password.

**Comment by FernetMenta** [comment] 2016-07-29 09:24
@Jalle19 I don't think that ffmpeg swscale logs belong to video playback. I would have looked into the log but I don't download and extract logs.

**Comment by Jalle19** [comment] 2016-07-29 09:37
@FernetMenta I sent you a link on Slack

**Comment by Leatherface75** [comment] 2016-07-29 10:13
Yes it's HLS streams and it seems they works as it should with pass option but not with htsp for some reason. Didn't work to force it to htsp with VLC etc to see if it's same there with htsp.

**Comment by Leatherface75** [comment] 2016-07-29 10:20
@FernetMenta reason i did that was because it was too big to paste on pastebin and that page crashed for me when trying especiallt the first one that was 11MB big..`

**Comment by Jalle19** [comment] 2016-07-29 10:23
@Leatherface75 there's a HTSP plugin for VLC (https://github.com/BtbN/vlc-htsp-plugin), you could try that and see how it works.

**Comment by FernetMenta** [comment] 2016-07-29 10:55
looks like tvh parser does something wrong. this looks like an invalid sequence of nal units:

```
20:52:55 T:140621782484736   DEBUG: ffmpeg[7FE50F648700]: [h264] nal_unit_type: 9, nal_ref_idc: 0
20:52:55 T:140621782484736   DEBUG: ffmpeg[7FE50F648700]: [h264] nal_unit_type: 1, nal_ref_idc: 1
20:52:55 T:140621782484736   DEBUG: Previous line repeats 3 times.
20:52:55 T:140621782484736   DEBUG: ffmpeg[7FE50F648700]: [h264] nal_unit_type: 7, nal_ref_idc: 1
20:52:55 T:140621782484736   DEBUG: ffmpeg[7FE50F648700]: [h264] nal_unit_type: 8, nal_ref_idc: 1
20:52:55 T:140621782484736   DEBUG: ffmpeg[7FE50F648700]: [h264] nal_unit_type: 9, nal_ref_idc: 0
```

**Comment by Jalle19** [comment] 2016-07-29 23:18
I think we should wait and see if @perexg can chip in on this. This would not be the first time we've barked up the wrong tree.

**Comment by Leatherface75** [comment] 2016-07-29 23:57
I have played a little more with this and seems to be same problem if i transcode the stream so it seems to be wrong when tvheadend does something with the stream.

**Comment by Jalle19** [comment] 2016-09-21 19:20
Like so many other playback related issues I think this is down to tvheadend not parsing the input stream properly. This means Kodi gets "junk" and playback doesn't work correctly. The fact that the VLC HTSP plugin behaves the same is indicative of this.

I would suggest you transcode the input tvheadend into pure MPEG-TS, the more like a standard-compliant DVB stream you make your input the bigger the chance that tvheadend can parse it properly.

Closing as invalid.

**Closed by Jalle19** 2016-09-21 19:20 UTC
Labels: Invalid

**Comment by Leatherface75** [comment] 2016-09-24 23:11
I am trying to use pass option like VLC uses as standard and other PVR addons like IPTVSimple but profiles doesn't seem to work anymore.
Only HTSP works with Kodi.

**Comment by John-Kenney** [comment] 2018-03-21 19:02
I was still having this problem with libreelec on an amlogic s912 box. disabling hardware decoding of h264 has fixed it for me, but increased cpu load a lot
