### ISSUE TITLE
Stuttering recordings with epg tag

### ISSUE THREAD

**Issue by Glenn-1990** [kodi-pvr/pvr.hts#75] opened 2015-07-24 18:09 UTC
https://github.com/xbmc/xbmc/pull/7601

As isengard final is already out, we might need to work around this?

Other addons don't suffer from this as they don't set an epg tag to recordings.

Not only active recordings seems affected, but actually all recordings with an epg tag, this is an serious issue on low power devices (rpi, imx6, android,...)

I can confirm that this works: https://github.com/Glenn-1990/pvr.hts/commit/b773579f14639b8695a70f86514f4bdbe9cb079a

@ksooo @Jalle19

**Comment by Jalle19** [comment] 2015-07-24 18:37
The addon won't be bumped before Isengard 15.1 anyway so if your Kodi fix gets merged this won't make any sense.

**Comment by Glenn-1990** [comment] 2015-07-30 18:05
Yes, then we need to fix this on the kodi side, too bad that nobody seems to take it serious.

Could you reproduce it? 
-> start kodi, play channel, watch cpu usage, open tv guide, record a show that is currently running,
play that show, monitor cpu usage again.

I even see a dramatic increase (live tv vs recording with epg tag) in cpu usage of kodi.bin on a i5.

**Comment by Glenn-1990** [comment] 2015-09-10 17:54
I've a PR for this on the kodi side, but I don't think that the fix will make it in isengard, we can add a workaround for the isengard branch? Not perfect, but users (including me :p) are suffering from this.
http://forum.kodi.tv/showthread.php?tid=234640

**Comment by Jalle19** [comment] 2015-09-11 06:06
If you PR a fix I'm sure we can accept it.

**Comment by Jalle19** [comment] 2015-09-20 21:22
Issue fixed in Isengard but we should leave this open until the issue is resolved for master too.

**Comment by Jalle19** [comment] 2015-12-19 05:46
@Glenn-1990 did a fix for this ever make it to Jarvis?

**Comment by Glenn-1990** [comment] 2015-12-19 22:52
Yes, I believe @ksooo did?

**Comment by Jalle19** [comment] 2015-12-20 14:19
If so, @ksooo can you please close this one?

**Comment by ksooo** [comment] 2015-12-20 17:51
I reverted the kodi core commit causing this, yes.

**Closed by ksooo** 2015-12-20 17:51 UTC
